// Phase ANALYZE — 70 questions
const ANALYZE_QUESTIONS = [
  { phase: "Analyze",
    q: "Une population a un écart-type σ = 12. On prélève des échantillons de taille n = 36. Quelle est l'erreur-type de la moyenne ?",
    o: ["12", "6", "0,33", "2"],
    a: 3,
    e: "Erreur-type = σ/√n = 12/√36 = 2. σ décrit les individus, σ/√n décrit la dispersion des moyennes d'échantillons." },

  { phase: "Analyze",
    q: "Une Green Belt veut savoir si le taux de pièces défectueuses (conforme / non conforme) diffère entre 4 fournisseurs. Quel test est le plus approprié ?",
    o: ["Test t à deux échantillons", "ANOVA à un facteur", "Test z à deux proportions", "Régression linéaire simple", "Test du chi-deux d'indépendance"],
    a: 4,
    e: "Données attributs et plus de deux groupes → chi-deux (tableau de contingence). Le test z à 2 proportions ne compare que deux groupes ; l'ANOVA exige des données continues." },

  { phase: "Analyze",
    q: "Un test d'hypothèse fournit une p-value de 0,03 pour un risque α fixé à 0,05. Quelle est la conclusion correcte ?",
    o: ["Ne pas rejeter H₀ : la différence n'est pas significative", "Accepter H₀ : les deux populations sont identiques", "Rejeter H₀ : la différence est statistiquement significative", "Le test n'est pas concluant, augmenter la taille d'échantillon"],
    a: 2,
    e: "Si p < α, on rejette H₀. 0,03 < 0,05 → rejet. On ne dit jamais « accepter H₀ », seulement « ne pas rejeter »." },

  { phase: "Analyze",
    q: "Un échantillon de n = 64 pièces donne une moyenne de 50 et un écart-type de 8. Quel est l'intervalle de confiance à 95 % pour la moyenne (z = 1,96) ?",
    o: ["[34,32 ; 65,68]", "[48,04 ; 51,96]", "[49,75 ; 50,25]", "[46,08 ; 53,92]"],
    a: 1,
    e: "IC = x̄ ± z × s/√n = 50 ± 1,96 × 8/8 = 50 ± 1,96 → [48,04 ; 51,96]. Utiliser s au lieu de s/√n donne le piège A." },

  { phase: "Analyze",
    q: "Une Green Belt compare le temps moyen de cycle (données continues, normales, variances égales) de 4 équipes de production. Quel test utiliser ?",
    o: ["Test t apparié", "Test de Kruskal-Wallis", "Test du chi-deux", "Test F de comparaison de variances", "ANOVA à un facteur"],
    a: 4,
    e: "Comparaison de moyennes de plus de deux groupes avec données normales → ANOVA à un facteur. Kruskal-Wallis est son équivalent non paramétrique." },

  { phase: "Analyze",
    q: "Les données de temps de traitement de deux services ne suivent pas une loi normale. Quel test non paramétrique remplace le test t à deux échantillons indépendants ?",
    o: ["Test de Mann-Whitney", "Test de Kruskal-Wallis", "Test des signes", "Test de Friedman", "Test de Mood pour les médianes"],
    a: 0,
    e: "Mann-Whitney compare deux échantillons indépendants. Kruskal-Wallis et Mood concernent k > 2 groupes ; signes et Friedman traitent des données appariées." },

  { phase: "Analyze",
    q: "Une Green Belt conclut qu'il existe une différence significative entre deux machines alors qu'en réalité elles sont identiques. Quel risque s'est matérialisé ?",
    o: ["Risque β, erreur de type II", "Puissance insuffisante du test", "Risque α, erreur de type I", "Erreur d'échantillonnage systématique"],
    a: 2,
    e: "Rejeter H₀ alors qu'elle est vraie = erreur de type I (α, faux positif). L'erreur de type II (β) consiste à manquer une différence réelle." },

  { phase: "Analyze",
    q: "Un test ne détecte pas une amélioration pourtant réelle du processus. Quel type d'erreur est commis ?",
    o: ["Erreur de type I (α)", "Erreur de type II (β)", "Erreur de mesure", "Erreur d'échantillonnage stratifié"],
    a: 1,
    e: "Ne pas rejeter H₀ alors qu'elle est fausse = erreur de type II, de probabilité β (faux négatif). La puissance du test est 1 − β." },

  { phase: "Analyze",
    q: "Qu'est-ce que la puissance d'un test statistique ?",
    o: ["La probabilité de rejeter H₀ quand elle est vraie", "La probabilité de détecter un effet réel (rejeter H₀ quand elle est fausse), soit 1 − β", "Le niveau de confiance 1 − α", "La taille de l'échantillon"],
    a: 1,
    e: "Puissance = 1 − β. Elle augmente avec n, avec la taille de l'effet à détecter et avec α ; elle diminue si la variabilité augmente." },

  { phase: "Analyze",
    q: "Quels leviers permettent d'augmenter la puissance d'un test sans changer α ?",
    o: ["Réduire la taille d'échantillon", "Augmenter la taille d'échantillon et/ou réduire la variabilité (meilleure mesure)", "Diminuer la taille de l'effet à détecter", "Utiliser un test bilatéral"],
    a: 1,
    e: "Plus n est grand et plus σ est petit, plus l'erreur-type diminue et plus le test détecte facilement une différence donnée." },

  { phase: "Analyze",
    q: "Quelle est la formulation correcte des hypothèses pour tester si la moyenne d'un processus diffère de la cible 50 ?",
    o: ["H₀ : μ ≠ 50 ; H₁ : μ = 50", "H₀ : μ = 50 ; H₁ : μ ≠ 50", "H₀ : x̄ = 50 ; H₁ : x̄ ≠ 50", "H₀ : μ > 50 ; H₁ : μ < 50"],
    a: 1,
    e: "H₀ contient toujours l'égalité (statu quo) et porte sur le paramètre de population μ, pas sur la statistique x̄. Test bilatéral car « diffère »." },

  { phase: "Analyze",
    q: "Un test unilatéral est approprié lorsque :",
    o: ["On ignore le sens de l'effet", "On ne s'intéresse qu'à un sens de la différence (ex. « le nouveau procédé est-il plus rapide ? »)", "Les données ne sont pas normales", "La taille d'échantillon est petite"],
    a: 1,
    e: "Test unilatéral : H₁ : μ < ou >. Test bilatéral : H₁ : μ ≠. Le choix se fait avant de voir les données." },

  { phase: "Analyze",
    q: "Quelle est la différence entre signification statistique et signification pratique ?",
    o: ["Aucune",
        "Une différence peut être statistiquement significative (p < α) mais trop petite pour avoir un intérêt opérationnel ou économique",
        "La signification pratique est toujours plus stricte",
        "La signification statistique n'existe que pour les grands échantillons"],
    a: 1,
    e: "Avec un très grand n, une différence infime devient significative. Il faut juger la taille de l'effet au regard des enjeux métier." },

  { phase: "Analyze",
    q: "Une Green Belt compare la moyenne d'un échantillon (n = 15, σ inconnu) à une valeur cible. Quel test utiliser ?",
    o: ["Test z à un échantillon", "Test t à un échantillon", "Test du chi-deux", "ANOVA"],
    a: 1,
    e: "σ inconnu (estimé par s) et petit échantillon → loi de Student, test t à 1 échantillon avec n − 1 degrés de liberté." },

  { phase: "Analyze",
    q: "Quand utilise-t-on un test t apparié plutôt qu'un test t à deux échantillons ?",
    o: ["Quand les échantillons sont de tailles différentes",
        "Quand chaque observation d'un groupe est naturellement liée à une observation de l'autre (avant/après sur la même pièce ou personne)",
        "Quand les variances sont inégales",
        "Quand les données sont attributs"],
    a: 1,
    e: "Le test apparié analyse les différences individuelles, éliminant la variabilité entre sujets : plus puissant quand l'appariement est pertinent." },

  { phase: "Analyze",
    q: "Avant un test t à deux échantillons, on veut vérifier l'égalité des variances de deux populations normales. Quel test ?",
    o: ["Test de Levene", "Test F (ou Bartlett)", "Test de Kruskal-Wallis", "Test du chi-deux d'ajustement"],
    a: 1,
    e: "Test F / Bartlett pour données normales ; Levene est plus robuste aux écarts à la normalité. Le résultat guide le choix du t (variances égales ou non)." },

  { phase: "Analyze",
    q: "Quel test compare les variances de plusieurs groupes de manière robuste à la non-normalité ?",
    o: ["Test F", "Test de Bartlett", "Test de Levene", "Test t"],
    a: 2,
    e: "Levene (basé sur les écarts absolus à la médiane) reste valide pour des données non normales, contrairement à F et Bartlett." },

  { phase: "Analyze",
    q: "Dans une ANOVA, que teste la statistique F ?",
    o: ["Le rapport variance inter-groupes / variance intra-groupes", "La différence entre deux médianes", "La normalité des résidus", "La corrélation entre deux facteurs"],
    a: 0,
    e: "F = MS_between / MS_within. Si les moyennes diffèrent, la variance entre groupes dépasse celle attendue du bruit intra-groupe → F grand, p petit." },

  { phase: "Analyze",
    q: "Une ANOVA à un facteur avec 4 groupes de 10 observations chacun. Quels sont les degrés de liberté inter-groupes et intra-groupes ?",
    o: ["3 et 36", "4 et 40", "3 et 39", "4 et 36"],
    a: 0,
    e: "df_between = k − 1 = 3 ; df_within = N − k = 40 − 4 = 36 ; df_total = N − 1 = 39." },

  { phase: "Analyze",
    q: "Une ANOVA donne p = 0,001. Que peut-on conclure ?",
    o: ["Toutes les moyennes sont différentes les unes des autres",
        "Au moins une moyenne diffère des autres ; des comparaisons multiples (Tukey) préciseront lesquelles",
        "Les variances sont égales",
        "Aucune moyenne ne diffère"],
    a: 1,
    e: "L'ANOVA est un test global. Pour identifier les paires différentes, on utilise des tests post-hoc (Tukey, Fisher, Dunnett)." },

  { phase: "Analyze",
    q: "Quelles sont les hypothèses de validité de l'ANOVA à un facteur ?",
    o: ["Résidus normaux, variances homogènes, observations indépendantes", "Données attributs, grands échantillons", "Corrélation forte entre groupes", "Variances différentes"],
    a: 0,
    e: "Normalité des résidus, homoscédasticité et indépendance. En cas de violation, utiliser Kruskal-Wallis ou l'ANOVA de Welch." },

  { phase: "Analyze",
    q: "Pourquoi ne pas réaliser plusieurs tests t deux à deux au lieu d'une ANOVA pour comparer 5 groupes ?",
    o: ["C'est plus long à calculer", "Le risque α global (familywise) s'accumule : 10 comparaisons à α = 0,05 donnent ≈ 40 % de chance d'au moins un faux positif", "Les tests t exigent des données attributs", "Il n'y a aucun inconvénient"],
    a: 1,
    e: "1 − (0,95)^10 ≈ 0,40. L'ANOVA contrôle le risque global en un seul test." },

  { phase: "Analyze",
    q: "Un tableau de contingence 3 × 4 est analysé par un test du chi-deux. Combien de degrés de liberté ?",
    o: ["12", "6", "7", "11"],
    a: 1,
    e: "df = (lignes − 1) × (colonnes − 1) = 2 × 3 = 6." },

  { phase: "Analyze",
    q: "Dans un test du chi-deux, comment calcule-t-on l'effectif attendu d'une cellule ?",
    o: ["(total ligne × total colonne) / total général", "total ligne / total colonne", "observé − attendu", "total général / nombre de cellules"],
    a: 0,
    e: "E = (L × C)/N sous l'hypothèse d'indépendance. La statistique est Σ (O − E)²/E. Règle : E ≥ 5 dans la plupart des cellules." },

  { phase: "Analyze",
    q: "Une entreprise veut savoir si le taux de défauts du nouveau lot (30/1 000) est différent de l'ancien (50/1 000). Quel test ?",
    o: ["Test t à deux échantillons", "Test à deux proportions", "ANOVA", "Test de Mann-Whitney"],
    a: 1,
    e: "Comparaison de deux proportions (données binaires) → test z à 2 proportions (équivalent au chi-deux 2 × 2)." },

  { phase: "Analyze",
    q: "On veut vérifier si le taux de défectueux du processus est bien inférieur à 2 % annoncé par le fournisseur. Quel test ?",
    o: ["Test à une proportion", "Test t à un échantillon", "Test de Kruskal-Wallis", "Test F"],
    a: 0,
    e: "Une proportion observée comparée à une valeur de référence → test à 1 proportion (H₀ : p = 0,02 ; H₁ : p < 0,02)." },

  { phase: "Analyze",
    q: "Quel test non paramétrique remplace l'ANOVA à un facteur lorsque les données ne sont pas normales ?",
    o: ["Mann-Whitney", "Kruskal-Wallis", "Wilcoxon signé", "Test des signes"],
    a: 1,
    e: "Kruskal-Wallis compare les médianes de k ≥ 2 groupes indépendants sur la base des rangs." },

  { phase: "Analyze",
    q: "Quel test non paramétrique remplace le test t apparié ?",
    o: ["Mann-Whitney", "Kruskal-Wallis", "Wilcoxon des rangs signés (ou test des signes)", "Test de Mood"],
    a: 2,
    e: "Wilcoxon signé (ou le test des signes, moins puissant) analyse les différences appariées sans hypothèse de normalité." },

  { phase: "Analyze",
    q: "Quel test non paramétrique remplace le test t à un échantillon ?",
    o: ["Test des signes / Wilcoxon à 1 échantillon", "Kruskal-Wallis", "Chi-deux", "Levene"],
    a: 0,
    e: "Pour comparer une médiane à une valeur cible sans normalité : test des signes à 1 échantillon ou Wilcoxon à 1 échantillon (si symétrie)." },

  { phase: "Analyze",
    q: "Comparé à Kruskal-Wallis, le test de Mood pour les médianes est :",
    o: ["Plus puissant en toutes circonstances", "Plus robuste aux valeurs extrêmes mais moins puissant", "Réservé à deux groupes", "Un test paramétrique"],
    a: 1,
    e: "Mood's median test compte les valeurs au-dessus/en dessous de la médiane globale (chi-deux) : robuste aux outliers, mais moins puissant que Kruskal-Wallis." },

  { phase: "Analyze",
    q: "Quelle est la principale différence entre un test paramétrique et un test non paramétrique ?",
    o: ["Le paramétrique est toujours plus rapide",
        "Le paramétrique suppose une distribution (souvent normale) et compare des moyennes ; le non paramétrique travaille sur les rangs/médianes sans cette hypothèse",
        "Le non paramétrique est plus puissant",
        "Le non paramétrique n'a pas de p-value"],
    a: 1,
    e: "Les tests non paramétriques sont plus robustes mais un peu moins puissants quand la normalité est effectivement respectée." },

  { phase: "Analyze",
    q: "Un coefficient de corrélation de Pearson r = −0,92 indique :",
    o: ["Une forte relation linéaire positive", "Une forte relation linéaire négative", "Une absence de relation", "Que X cause une baisse de Y"],
    a: 1,
    e: "r varie de −1 à +1 ; |r| proche de 1 = relation linéaire forte ; le signe donne le sens. La corrélation n'implique pas la causalité." },

  { phase: "Analyze",
    q: "Un coefficient r = 0,05 entre deux variables signifie :",
    o: ["Il n'y a aucune relation d'aucune sorte", "Il n'y a pas de relation linéaire notable (une relation non linéaire reste possible)", "La relation est forte", "X et Y sont indépendants avec certitude"],
    a: 1,
    e: "Pearson ne mesure que la linéarité. Une relation en U donne r ≈ 0. Toujours regarder le nuage de points." },

  { phase: "Analyze",
    q: "Quel coefficient de corrélation convient pour des données ordinales ou non normales ?",
    o: ["Pearson", "Spearman (corrélation des rangs)", "Kappa", "Cp"],
    a: 1,
    e: "Spearman calcule la corrélation sur les rangs ; il capte les relations monotones même non linéaires." },

  { phase: "Analyze",
    q: "Les ventes de glaces et le nombre de noyades sont fortement corrélés. Quelle est l'explication la plus vraisemblable ?",
    o: ["Manger des glaces cause les noyades", "Une variable cachée (la température estivale) influence les deux", "Une coïncidence sans intérêt", "Les noyades font vendre des glaces"],
    a: 1,
    e: "Corrélation ≠ causalité : une variable confondante (lurking variable) peut expliquer la relation. Seule l'expérimentation établit la causalité." },

  { phase: "Analyze",
    q: "Quelle est la taille d'échantillon nécessaire pour estimer une moyenne avec une marge d'erreur E = 2, σ = 10, à 95 % (z = 1,96) ?",
    o: ["10", "97", "25", "384"],
    a: 1,
    e: "n = (z σ / E)² = (1,96 × 10 / 2)² = 9,8² ≈ 96,04 → arrondir à 97." },

  { phase: "Analyze",
    q: "Pour estimer une proportion à ±3 % avec 95 % de confiance sans information préalable (p = 0,5), quelle taille d'échantillon ?",
    o: ["≈ 1 068", "≈ 385", "≈ 100", "≈ 30"],
    a: 0,
    e: "n = z² p(1−p)/E² = 1,96² × 0,25 / 0,03² = 0,9604 / 0,0009 ≈ 1 067,1 → 1 068. Pour E = 5 %, n ≈ 385." },

  { phase: "Analyze",
    q: "Si l'on divise la marge d'erreur souhaitée par 2, la taille d'échantillon nécessaire :",
    o: ["Double", "Est divisée par 2", "Quadruple", "Reste identique"],
    a: 2,
    e: "n ∝ 1/E². Diviser E par 2 multiplie n par 4. L'erreur-type décroît en 1/√n." },

  { phase: "Analyze",
    q: "Quelle est l'interprétation correcte d'un intervalle de confiance à 95 % pour μ : [48 ; 52] ?",
    o: ["95 % des données sont entre 48 et 52",
        "Si l'on répétait l'échantillonnage, 95 % des intervalles ainsi construits contiendraient μ",
        "Il y a 95 % de chances que x̄ soit entre 48 et 52",
        "μ est certainement dans [48 ; 52]"],
    a: 1,
    e: "L'IC porte sur le paramètre μ et sur la procédure ; il ne décrit pas la dispersion des données individuelles (ce serait un intervalle de tolérance)." },

  { phase: "Analyze",
    q: "Pour un échantillon de taille n = 20 avec σ inconnu, quelle distribution utilise-t-on pour construire l'IC de la moyenne ?",
    o: ["Loi normale (z)", "Loi de Student (t) à 19 ddl", "Loi du chi-deux à 19 ddl", "Loi F"],
    a: 1,
    e: "σ inconnu → t de Student, n − 1 = 19 degrés de liberté. La loi t a des queues plus lourdes que la normale, élargissant l'IC." },

  { phase: "Analyze",
    q: "Quelle distribution est utilisée pour construire l'intervalle de confiance d'une variance ou d'un écart-type ?",
    o: ["Loi normale", "Loi de Student", "Loi du chi-deux", "Loi binomiale"],
    a: 2,
    e: "(n − 1)s²/σ² suit une loi du chi-deux à n − 1 ddl. La loi F sert à comparer deux variances." },

  { phase: "Analyze",
    q: "Quand n augmente, l'intervalle de confiance à 95 % pour la moyenne :",
    o: ["S'élargit", "Se rétrécit", "Reste constant", "Devient asymétrique"],
    a: 1,
    e: "La demi-largeur est z × σ/√n : elle diminue en 1/√n. Passer de n = 25 à n = 100 divise la largeur par 2." },

  { phase: "Analyze",
    q: "Une distribution de population est fortement asymétrique. Avec des échantillons de taille n = 50, la distribution des moyennes x̄ sera :",
    o: ["Fortement asymétrique", "Approximativement normale (théorème de la limite centrale)", "Uniforme", "Bimodale"],
    a: 1,
    e: "TLC : dès n ≈ 30, la distribution d'échantillonnage de la moyenne est proche de la normale, quel que soit la loi mère." },

  { phase: "Analyze",
    q: "Une étude multi-vari montre que la variation « pièce à pièce » est bien plus grande que la variation « intra-pièce » et « temporelle ». Où faut-il chercher les causes ?",
    o: ["Dans la dérive des réglages au cours du temps", "Dans les facteurs qui varient d'une pièce à l'autre (matière, positionnement, cycle)", "Dans l'usure de l'outil", "Dans l'instrument de mesure"],
    a: 1,
    e: "Le multi-vari décompose la variation en familles (positionnelle, cyclique, temporelle) pour orienter l'analyse vers la famille dominante." },

  { phase: "Analyze",
    q: "La méthode des « 5 Pourquoi » sert à :",
    o: ["Prioriser les causes par fréquence", "Remonter d'un symptôme à la cause racine en questionnant successivement", "Calculer la puissance d'un test", "Choisir la taille d'échantillon"],
    a: 1,
    e: "En demandant « pourquoi ? » de façon itérative, on dépasse les symptômes et les causes apparentes. À valider ensuite par des données." },

  { phase: "Analyze",
    q: "Une équipe a listé 40 causes potentielles via un Ishikawa. Quelle est l'étape suivante appropriée ?",
    o: ["Mettre en œuvre des solutions pour les 40 causes",
        "Prioriser (vote, matrice X-Y, Pareto) puis vérifier les causes retenues par des données et des tests",
        "Clôturer le projet",
        "Rédiger le plan de contrôle"],
    a: 1,
    e: "Les causes de l'Ishikawa sont des hypothèses. L'Analyze consiste à les réduire puis à les confirmer statistiquement (tests, graphiques, régression)." },

  { phase: "Analyze",
    q: "Un diagramme de Pareto montre que 3 types de défauts sur 12 représentent 78 % des occurrences. Quelle décision en découle ?",
    o: ["Traiter les 12 types en parallèle", "Concentrer l'analyse des causes sur ces 3 types", "Ignorer ces 3 types", "Refaire le Pareto sur les 9 autres"],
    a: 1,
    e: "Le Pareto oriente l'effort vers les « vital few ». On peut ensuite faire un Pareto de second niveau (par cause) sur ces 3 types." },

  { phase: "Analyze",
    q: "Une régression linéaire simple donne Y = 5 + 2X avec p(pente) = 0,001 et R² = 0,15. Comment interpréter ?",
    o: ["X n'a aucun effet", "La pente est significative mais X n'explique que 15 % de la variation de Y ; d'autres facteurs interviennent", "Le modèle prédit très bien Y", "R² est forcément faux"],
    a: 1,
    e: "Une pente significative n'implique pas un modèle explicatif fort. Un faible R² invite à chercher d'autres X ou une relation non linéaire." },

  { phase: "Analyze",
    q: "Dans une régression, qu'est-ce qu'un résidu ?",
    o: ["La pente de la droite", "L'écart entre la valeur observée et la valeur prédite (Y − Ŷ)", "L'ordonnée à l'origine", "Le coefficient de corrélation"],
    a: 1,
    e: "Résidu = observé − ajusté. Leur analyse (normalité, variance constante, indépendance) valide le modèle." },

  { phase: "Analyze",
    q: "La droite des moindres carrés minimise :",
    o: ["La somme des résidus", "La somme des carrés des résidus", "Le plus grand résidu", "La somme des valeurs absolues des résidus"],
    a: 1,
    e: "Moindres carrés ordinaires : min Σ(Yᵢ − Ŷᵢ)². La somme simple des résidus est toujours nulle." },

  { phase: "Analyze",
    q: "Un modèle de régression est ajusté sur des X compris entre 10 et 50. Utiliser le modèle pour prédire Y à X = 90 est :",
    o: ["Une interpolation fiable", "Une extrapolation risquée car la relation n'est pas vérifiée hors de la plage étudiée", "Recommandé pour tester le modèle", "Impossible mathématiquement"],
    a: 1,
    e: "L'extrapolation suppose que la relation reste identique hors du domaine observé, ce qui n'est pas garanti." },

  { phase: "Analyze",
    q: "Une Green Belt observe, dans un nuage de points, une relation en forme de courbe. Que faire ?",
    o: ["Utiliser Pearson quand même", "Envisager une régression non linéaire ou une transformation (quadratique, log)", "Conclure à l'absence de relation", "Supprimer les points extrêmes"],
    a: 1,
    e: "Une relation curviligne n'est pas bien capturée par r ni par une droite ; on ajoute un terme X² ou on transforme les variables." },

  { phase: "Analyze",
    q: "Une p-value de 0,08 est obtenue avec α = 0,05. Quelle conclusion ?",
    o: ["Rejeter H₀", "Ne pas rejeter H₀ : la différence n'est pas statistiquement significative au seuil de 5 %", "H₀ est prouvée vraie", "Changer α à 0,10 pour rejeter"],
    a: 1,
    e: "p ≥ α → on ne rejette pas H₀. Modifier α après coup pour obtenir la significativité est une mauvaise pratique (p-hacking)." },

  { phase: "Analyze",
    q: "Qu'est-ce que la p-value ?",
    o: ["La probabilité que H₀ soit vraie",
        "La probabilité d'observer un résultat au moins aussi extrême que celui obtenu, si H₀ est vraie",
        "La probabilité que H₁ soit vraie",
        "Le risque β"],
    a: 1,
    e: "La p-value est conditionnelle à H₀ vraie. Elle ne donne pas la probabilité de H₀ ni celle de H₁." },

  { phase: "Analyze",
    q: "Dans un test à deux échantillons, la statistique t calculée est 2,8 pour une valeur critique de 2,05 (α = 0,05, bilatéral). Que conclure ?",
    o: ["Ne pas rejeter H₀", "Rejeter H₀ : la différence est significative", "Test non concluant", "Il faut refaire le test unilatéral"],
    a: 1,
    e: "|t calculé| > t critique → rejet de H₀. Équivalent à p < α." },

  { phase: "Analyze",
    q: "Qu'est-ce que la « valeur critique » d'un test ?",
    o: ["La p-value", "Le seuil de la statistique de test au-delà duquel on rejette H₀, déterminé par α et les ddl", "La moyenne de l'échantillon", "La taille d'effet"],
    a: 1,
    e: "Deux approches équivalentes : comparer la statistique à la valeur critique, ou comparer la p-value à α." },

  { phase: "Analyze",
    q: "Une Green Belt veut tester si les temps de traitement (données continues normales) diffèrent entre deux agences. Variances jugées égales. Quel test ?",
    o: ["Test t à deux échantillons (variances égales, poolées)", "Test t apparié", "Test à deux proportions", "Chi-deux"],
    a: 0,
    e: "Deux groupes indépendants, données continues normales → test t à 2 échantillons. Si variances inégales : test t de Welch." },

  { phase: "Analyze",
    q: "Quel graphique compare visuellement la distribution de plusieurs groupes (médiane, dispersion, outliers) avant un test ANOVA ou Kruskal-Wallis ?",
    o: ["L'histogramme unique", "Les box plots côte à côte", "Le diagramme de Pareto", "La carte de contrôle"],
    a: 1,
    e: "Les box plots juxtaposés permettent d'apprécier les différences de position et de dispersion et de repérer les valeurs atypiques." },

  { phase: "Analyze",
    q: "Le diagramme des effets principaux (main effects plot) d'une ANOVA montre une ligne quasi horizontale pour le facteur « équipe ». Interprétation ?",
    o: ["L'équipe a un fort effet", "L'équipe n'a que peu ou pas d'effet sur la moyenne de la réponse", "Il y a une interaction", "Les données sont non normales"],
    a: 1,
    e: "Une pente nulle entre niveaux = moyennes similaires = effet faible. Une forte pente signale un facteur influent." },

  { phase: "Analyze",
    q: "Une analyse révèle que la variation intra-équipe est bien plus grande que la variation inter-équipes. Que conclure ?",
    o: ["Il faut former une équipe en particulier", "Le facteur « équipe » n'explique pas la variation ; chercher d'autres X", "L'ANOVA est invalide", "Le processus est capable"],
    a: 1,
    e: "Si les groupes se ressemblent (grande dispersion interne, moyennes proches), F est petit : le facteur n'est pas la cause majeure." },

  { phase: "Analyze",
    q: "Un test de normalité sur 500 données donne p = 0,02 alors que l'histogramme semble presque normal. Comment agir ?",
    o: ["Abandonner l'analyse", "Considérer que les tests de moyennes restent robustes (TLC, grand n) et juger de l'ampleur pratique de l'écart à la normalité", "Supprimer 20 % des données", "Considérer que les données sont uniformes"],
    a: 1,
    e: "Avec de grands échantillons, les tests de normalité détectent des écarts minimes sans conséquence. Les tests t/ANOVA sont robustes grâce au TLC." },

  { phase: "Analyze",
    q: "Quelle affirmation sur α (niveau de signification) est correcte ?",
    o: ["α est calculé après le test", "α est fixé avant le test et représente le risque accepté de rejeter H₀ à tort", "α = 1 − puissance", "α est toujours 0,05"],
    a: 1,
    e: "α est un choix a priori (souvent 5 %, parfois 1 % ou 10 % selon les enjeux). La p-value, elle, est calculée à partir des données." },

  { phase: "Analyze",
    q: "Une Green Belt collecte 5 mesures par pièce sur 3 pièces consécutives, toutes les heures pendant 8 heures. Quel outil graphique révèle quelle famille de variation domine ?",
    o: ["Diagramme de Pareto", "Graphique multi-vari", "Histogramme", "Diagramme d'affinités"],
    a: 1,
    e: "Le multi-vari chart représente la variation intra-pièce, pièce à pièce et temporelle sur un même graphique sans manipuler le processus." },

  { phase: "Analyze",
    q: "Après avoir confirmé 3 causes racines par des tests statistiques, quel est le livrable principal de sortie de la phase Analyze ?",
    o: ["Le plan de contrôle", "La liste des X vitaux validés par les données, avec leur contribution à Y", "La charte de projet", "Le SIPOC"],
    a: 1,
    e: "Analyze se termine par l'identification des « vital few X » prouvés (pas seulement supposés), base de la phase Improve." },

  { phase: "Analyze",
    q: "Une régression donne un coefficient de pente de −0,8 avec p = 0,002. Signification ?",
    o: ["Y augmente de 0,8 quand X augmente de 1", "Y diminue en moyenne de 0,8 unité par unité de X, et cette relation est significative", "80 % de Y est expliqué par X", "La corrélation est de −0,002"],
    a: 1,
    e: "La pente négative indique une relation inverse ; p < 0,05 confirme qu'elle diffère significativement de zéro." },

  { phase: "Analyze",
    q: "Un point très éloigné des autres dans un nuage de points influence fortement la droite de régression. Comment le nomme-t-on ?",
    o: ["Un résidu standardisé", "Un point influent (à fort effet de levier)", "Une valeur ajustée", "Un degré de liberté"],
    a: 1,
    e: "Il faut vérifier si ce point est une erreur de mesure/saisie ou une observation réelle avant de décider de le retirer ou non." },

  { phase: "Analyze",
    q: "L'hypothèse d'indépendance des résidus est vérifiée par :",
    o: ["Le graphique des résidus en fonction de l'ordre des observations (absence de tendance ou de cycle)", "L'histogramme des résidus", "La droite de Henry", "Le R²"],
    a: 0,
    e: "Résidus vs ordre révèle l'autocorrélation (ex. dérive temporelle). Normalité → droite de Henry ; variance constante → résidus vs ajustés." },

  { phase: "Analyze",
    q: "Une entreprise compare la satisfaction (échelle 1 à 5) entre 3 canaux de vente. Quel test est le plus approprié ?",
    o: ["ANOVA classique sans réserve", "Kruskal-Wallis (données ordinales)", "Test t", "Test F"],
    a: 1,
    e: "Une échelle de Likert est ordinale ; un test sur les rangs (Kruskal-Wallis) est plus approprié qu'une comparaison de moyennes." },

  { phase: "Analyze",
    q: "Quelle affirmation concernant la loi de Student (t) est correcte ?",
    o: ["Elle est plus étroite que la loi normale", "Elle tend vers la loi normale quand les degrés de liberté augmentent", "Elle est asymétrique", "Elle ne s'utilise que pour n > 30"],
    a: 1,
    e: "La loi t a des queues plus épaisses pour tenir compte de l'incertitude sur s ; au-delà de ~30 ddl elle est quasi identique à la normale." },

  { phase: "Analyze",
    q: "Une Green Belt compare la médiane des temps d'attente de 3 guichets ; les données présentent de nombreuses valeurs extrêmes. Quel test privilégier ?",
    o: ["ANOVA à un facteur", "Test de Mood pour les médianes", "Test t à deux échantillons", "Test à deux proportions"],
    a: 1,
    e: "k > 2 groupes, données non normales avec outliers → Mood's median test, plus robuste aux valeurs extrêmes que Kruskal-Wallis. L'ANOVA suppose la normalité." }
];
