// Phase CONTROL — 30 questions
const CONTROL_QUESTIONS = [
  { phase: "Control",
    q: "Sur une carte X̄-R, un point de moyenne dépasse la limite de contrôle supérieure (LCS) mais reste à l'intérieur de la spécification client. Que doit faire l'opérateur ?",
    o: ["Ne rien faire, le produit est conforme", "Rechercher et traiter une cause spéciale", "Élargir les limites de contrôle", "Recentrer le processus sur la cible"],
    a: 1,
    e: "Les limites de contrôle reflètent la voix du processus, pas celle du client. Un point hors LCS signale une cause spéciale à investiguer, même si la pièce est dans la spécification." },

  { phase: "Control",
    q: "Quel document précise, pour chaque caractéristique clé, la méthode de mesure, la taille d'échantillon, la fréquence et le plan de réaction en cas de dérive ?",
    o: ["Le plan de contrôle", "L'AMDEC processus", "La cartographie du flux de valeur", "Le tableau de bord de projet"],
    a: 0,
    e: "Le plan de contrôle formalise la surveillance du processus après amélioration : quoi mesurer, comment, à quelle fréquence et que faire en cas d'anomalie." },

  { phase: "Control",
    q: "Un processus est statistiquement sous contrôle (aucun signal sur la carte) mais son Cpk est de 0,7. Quelle est l'action appropriée ?",
    o: ["Attendre l'apparition d'une cause spéciale pour agir", "Travailler sur la réduction de la variation de cause commune", "Resserrer les limites de contrôle pour détecter les dérives", "Former les opérateurs à réagir plus vite aux points hors limites"],
    a: 1,
    e: "Sous contrôle mais non capable : la variation naturelle (cause commune) est trop grande. Il faut améliorer fondamentalement le processus, pas ajuster les limites." },

  { phase: "Control",
    q: "On mesure le diamètre de pièces par sous-groupes de 4 toutes les heures. Quelle carte de contrôle utiliser ?",
    o: ["Carte I-MR", "Carte X̄-R", "Carte X̄-S", "Carte p"],
    a: 1,
    e: "Données continues, sous-groupes de taille 2 à 9 → X̄-R. Taille ≥ 10 → X̄-S (l'écart-type devient plus efficace que l'étendue). n = 1 → I-MR." },

  { phase: "Control",
    q: "Une caractéristique chimique est mesurée une fois par lot (une seule valeur par lot). Quelle carte convient ?",
    o: ["Carte X̄-R", "Carte I-MR (valeurs individuelles et étendues mobiles)", "Carte np", "Carte c"],
    a: 1,
    e: "Sous-groupe de taille 1 (mesures coûteuses, lots, processus lents) → carte I-MR. L'étendue mobile entre valeurs successives estime σ." },

  { phase: "Control",
    q: "On mesure le poids de sachets par sous-groupes de 15 unités. Quelle carte est la plus appropriée ?",
    o: ["X̄-R", "X̄-S", "I-MR", "u"],
    a: 1,
    e: "Pour n ≥ 10, l'étendue perd en efficacité ; on utilise X̄-S (moyenne et écart-type)." },

  { phase: "Control",
    q: "Chaque jour, on inspecte 200 factures (taille fixe) et on compte le nombre de factures erronées. Quelle carte utiliser ?",
    o: ["Carte p", "Carte np", "Carte c", "Carte u"],
    a: 1,
    e: "Défectueux (binomial) avec taille d'échantillon constante → carte np (nombre de défectueux). Si la taille variait, on utiliserait la carte p (proportion)." },

  { phase: "Control",
    q: "Chaque semaine, on contrôle toutes les commandes livrées (volume variable) et on calcule la proportion de commandes en retard. Quelle carte ?",
    o: ["Carte p", "Carte np", "Carte c", "Carte I-MR"],
    a: 0,
    e: "Proportion de défectueux avec taille d'échantillon variable → carte p ; ses limites de contrôle varient avec n." },

  { phase: "Control",
    q: "On compte le nombre de fautes de frappe par page dans des documents de longueur identique. Quelle carte ?",
    o: ["Carte p", "Carte np", "Carte c", "Carte u"],
    a: 2,
    e: "Comptage de défauts (Poisson) sur une aire d'opportunité constante → carte c. Aire variable → carte u." },

  { phase: "Control",
    q: "Quelle affirmation distingue correctement les limites de contrôle des limites de spécification ?",
    o: ["Elles sont identiques", "Les limites de contrôle sont calculées à partir des données du processus (±3σ) ; les limites de spécification viennent des exigences client", "Les limites de spécification sont toujours plus étroites", "Les limites de contrôle sont fixées par le client"],
    a: 1,
    e: "Ne jamais tracer les limites de spécification sur une carte X̄ : la moyenne d'un sous-groupe peut être dans la spec alors que des individus sont hors spec." },

  { phase: "Control",
    q: "Selon les règles de Western Electric, laquelle de ces situations signale une cause spéciale ?",
    o: ["1 point entre 1σ et 2σ", "8 (ou 7) points consécutifs du même côté de la ligne centrale", "2 points consécutifs alternant au-dessus et en dessous de la moyenne", "Tous les points dans ±1σ"],
    a: 1,
    e: "Règles WE : 1 point > 3σ ; 2 sur 3 > 2σ du même côté ; 4 sur 5 > 1σ du même côté ; 8 consécutifs du même côté (décalage de moyenne)." },

  { phase: "Control",
    q: "Sur une carte, 2 points sur 3 consécutifs se situent au-delà de 2σ du même côté de la moyenne. Que conclure ?",
    o: ["Le processus est sous contrôle", "Signal de cause spéciale (règle Western Electric n° 2)", "Il faut recalculer les limites", "C'est normal si la spec est respectée"],
    a: 1,
    e: "La probabilité de ce motif sous cause commune est très faible ; il indique un décalage de la moyenne." },

  { phase: "Control",
    q: "Une suite de 7 points consécutifs strictement croissants apparaît sur la carte. Interprétation ?",
    o: ["Variation aléatoire normale", "Tendance : signal de cause spéciale (usure d'outil, dérive)", "Le processus s'améliore, rien à faire", "Erreur de calcul des limites"],
    a: 1,
    e: "Une tendance (run ascendant ou descendant de 6–7 points) est un signal non aléatoire à investiguer." },

  { phase: "Control",
    q: "Sur une carte X̄-R, laquelle des deux cartes doit être interprétée en premier ?",
    o: ["La carte X̄", "La carte R", "Peu importe", "Les deux simultanément sans priorité"],
    a: 1,
    e: "La carte R d'abord : si la dispersion n'est pas maîtrisée, les limites de la carte X̄ (calculées à partir de R̄) ne sont pas fiables." },

  { phase: "Control",
    q: "Pour une carte X̄ avec n = 5, X̿ = 50 et R̄ = 4 (A₂ = 0,577), quelles sont les limites de contrôle ?",
    o: ["[46 ; 54]", "[47,69 ; 52,31]", "[38 ; 62]", "[49,42 ; 50,58]"],
    a: 1,
    e: "LC = X̿ ± A₂ R̄ = 50 ± 0,577 × 4 = 50 ± 2,31 → [47,69 ; 52,31]." },

  { phase: "Control",
    q: "Pour une carte R avec n = 5 et R̄ = 4 (D₃ = 0 ; D₄ = 2,114), quelles sont les limites ?",
    o: ["LCI = 0 ; LCS = 8,46", "LCI = 4 ; LCS = 8", "LCI = −4,46 ; LCS = 8,46", "LCI = 0 ; LCS = 4"],
    a: 0,
    e: "LCS_R = D₄ R̄ = 2,114 × 4 = 8,46 ; LCI_R = D₃ R̄ = 0 (D₃ = 0 pour n ≤ 6)." },

  { phase: "Control",
    q: "Une carte p a p̄ = 0,04 et n = 100. Quelle est la limite de contrôle supérieure ?",
    o: ["0,0988", "0,16", "0,0596", "0,04"],
    a: 0,
    e: "LCS = p̄ + 3√(p̄(1−p̄)/n) = 0,04 + 3√(0,04×0,96/100) = 0,04 + 3 × 0,0196 = 0,0988. LCI = 0,04 − 0,0588 < 0 → 0." },

  { phase: "Control",
    q: "Une carte c a c̄ = 9. Quelles sont ses limites de contrôle ?",
    o: ["[0 ; 18]", "[0 ; 27]", "[6 ; 12]", "[3 ; 15]"],
    a: 0,
    e: "LC = c̄ ± 3√c̄ = 9 ± 3 × 3 = 9 ± 9 → LCI = 0 ; LCS = 18." },

  { phase: "Control",
    q: "Qu'est-ce que le « sous-groupe rationnel » en SPC ?",
    o: ["Un groupe d'opérateurs formés", "Un échantillon prélevé de façon à ne contenir que de la variation de cause commune (pièces consécutives, même conditions), pour que les causes spéciales apparaissent entre sous-groupes", "Un échantillon de taille 30", "Un échantillon aléatoire sur toute la journée"],
    a: 1,
    e: "Le sous-groupe rationnel minimise la variation intra-groupe et maximise la chance de détecter les changements entre groupes." },

  { phase: "Control",
    q: "Un opérateur ajuste la machine après chaque pièce mesurée légèrement au-dessus ou en dessous de la cible, bien que le processus soit sous contrôle. Quel en est l'effet ?",
    o: ["La variation diminue", "La variation augmente (sur-ajustement / tampering, expérience de l'entonnoir de Deming)", "Aucun effet", "Le Cpk s'améliore"],
    a: 1,
    e: "Réagir aux causes communes comme si elles étaient spéciales ajoute de la variation. Il ne faut ajuster que sur signal de la carte." },

  { phase: "Control",
    q: "Quelle carte de contrôle est la plus sensible pour détecter de petits décalages persistants de la moyenne (< 1,5σ) ?",
    o: ["Carte X̄-R classique", "Carte CUSUM ou EWMA", "Carte p", "Carte c"],
    a: 1,
    e: "CUSUM (somme cumulée) et EWMA (moyenne mobile pondérée exponentiellement) accumulent l'information des points précédents, détectant plus vite les petits shifts." },

  { phase: "Control",
    q: "Après amélioration, l'équipe recalcule les limites de contrôle. Quand est-il légitime de le faire ?",
    o: ["À chaque point hors limites", "Lorsqu'un changement de processus connu et confirmé a modifié durablement sa moyenne ou sa dispersion", "Chaque jour", "Jamais"],
    a: 1,
    e: "Les limites se recalculent quand le processus a réellement changé (nouvelle phase), pas pour faire « rentrer » les points." },

  { phase: "Control",
    q: "Combien de sous-groupes recommande-t-on en général pour établir des limites de contrôle initiales fiables ?",
    o: ["5", "10", "20 à 25", "100"],
    a: 2,
    e: "Environ 20–25 sous-groupes (≈ 100 valeurs individuelles) permettent des estimations stables de la moyenne et de la dispersion." },

  { phase: "Control",
    q: "Quel est l'objectif du plan de réaction (OCAP, Out-of-Control Action Plan) ?",
    o: ["Définir les objectifs financiers", "Indiquer précisément qui fait quoi lorsqu'un signal apparaît sur la carte de contrôle", "Calculer le Cpk", "Sélectionner les projets"],
    a: 1,
    e: "L'OCAP est intégré au plan de contrôle : il standardise le diagnostic et la réaction pour éviter l'improvisation et le tampering." },

  { phase: "Control",
    q: "Quel élément est indispensable pour pérenniser les gains d'un projet Six Sigma ?",
    o: ["La dissolution rapide de l'équipe", "Le transfert formel au Process Owner avec standards documentés, formation et plan de contrôle", "Le maintien du Black Belt sur le processus indéfiniment", "L'arrêt de toute mesure"],
    a: 1,
    e: "Sans appropriation par le propriétaire du processus et sans standardisation (travail standard, visuels, audits), les gains s'érodent." },

  { phase: "Control",
    q: "Qu'est-ce que le « travail standard » (standard work) ?",
    o: ["Une norme ISO", "La description documentée de la meilleure méthode connue : séquence, takt, en-cours standard", "Une carte de contrôle", "Une réunion hebdomadaire"],
    a: 1,
    e: "Le travail standard fixe la base de l'amélioration continue : sans standard, pas de mesure de l'écart ni de kaizen durable." },

  { phase: "Control",
    q: "Le management visuel (tableaux, andon, marquages au sol) sert principalement à :",
    o: ["Décorer l'atelier", "Rendre l'état normal/anormal du processus immédiatement visible par tous pour déclencher une réaction rapide", "Remplacer les cartes de contrôle", "Mesurer la capabilité"],
    a: 1,
    e: "Le visuel expose les écarts au standard en temps réel et soutient la discipline du plan de contrôle." },

  { phase: "Control",
    q: "Une caractéristique est mesurée par sous-groupes de 3 mais la carte R montre de nombreux zéros. Quelle en est la cause probable ?",
    o: ["Le processus est parfait", "La résolution de l'instrument est insuffisante par rapport à la variation du processus", "Il faut passer à une carte p", "Les limites sont mal calculées"],
    a: 1,
    e: "Des étendues nulles fréquentes indiquent que l'instrument ne distingue pas les pièces entre elles : problème de discrimination (règle du 1/10)." },

  { phase: "Control",
    q: "Quelle est la différence essentielle entre une cause commune et une cause spéciale ?",
    o: ["La cause commune est plus grave",
        "La cause commune est inhérente au système et toujours présente (variation aléatoire) ; la cause spéciale est ponctuelle, assignable et extérieure au système habituel",
        "La cause spéciale ne concerne que les services",
        "Il n'y a pas de différence"],
    a: 1,
    e: "Causes communes → action sur le système (management, projet DMAIC). Causes spéciales → action locale immédiate (OCAP)." },

  { phase: "Control",
    q: "Lors de la clôture du projet, quel livrable capitalise l'expérience pour les projets futurs ?",
    o: ["Le rapport de leçons apprises (lessons learned) et la documentation finale", "Le SIPOC", "La droite de Henry", "L'histogramme initial"],
    a: 0,
    e: "La clôture comprend : validation des gains par la finance, transfert au Process Owner, documentation, leçons apprises, reconnaissance de l'équipe." }
];
