// Phase DEFINE — 50 questions
const DEFINE_QUESTIONS = [
  { phase: "Define",
    q: "Dans un projet de réduction du délai de traitement des factures fournisseurs, l'équipe classe les étapes du processus. Laquelle relève du BNVA (Business Non-Value-Added) ?",
    o: ["La saisie du montant de la facture dans l'ERP",
        "L'attente de la facture dans la corbeille du comptable",
        "Le double contrôle exigé par la réglementation comptable",
        "La correction d'une erreur de saisie détectée au paiement"],
    a: 2,
    e: "Le BNVA n'apporte pas de valeur au client mais est requis par l'entreprise ou la réglementation. L'attente et la reprise sont du NVA pur ; la saisie est VA." },

  { phase: "Define",
    q: "Lequel de ces énoncés constitue un énoncé du problème (Problem Statement) correctement formulé pour une charte de projet ?",
    o: ["Le taux de retours clients de la ligne B est passé de 2 % à 5,5 % depuis janvier, soit 120 k€ de coûts",
        "Les clients sont mécontents de la qualité et il faut réduire les retours rapidement",
        "L'équipe va analyser les causes des retours et mettre en place un plan d'action",
        "Le manque de formation des opérateurs génère trop de retours sur la ligne B"],
    a: 0,
    e: "Un bon énoncé de problème est factuel et quantifié (quoi, où, quand, ampleur), sans cause supposée ni solution. B est vague, C est un plan, D présume la cause." },

  { phase: "Define",
    q: "Une entreprise de livraison recueille la voix du client : « Je veux recevoir mon colis rapidement ». Quel énoncé traduit correctement ce besoin en CTQ ?",
    o: ["Améliorer la satisfaction client sur la livraison",
        "Réduire le nombre de plaintes liées aux délais",
        "Le client souhaite une livraison rapide et fiable",
        "Délai de livraison ≤ 48 h pour 95 % des colis"],
    a: 3,
    e: "Un CTQ est une exigence mesurable et spécifique dérivée de la VOC, avec cible et limite. A et C restent qualitatifs ; B est un indicateur de résultat, pas une exigence client." },

  { phase: "Define",
    q: "Une ligne d'assemblage dispose de 450 minutes de production par jour. La demande client est de 900 unités par jour. Quel est le takt time ?",
    o: ["30 secondes", "2 minutes", "0,5 unité par minute", "20 secondes"],
    a: 0,
    e: "Takt time = temps disponible / demande client = 450 min / 900 unités = 0,5 min = 30 s par unité. Inverser la formule donne 2 unités/min (pas un temps)." },

  { phase: "Define",
    q: "Dans la classification des coûts de la non-qualité (COPQ), lequel de ces éléments est un coût d'échec externe ?",
    o: ["Le tri des pièces non conformes en fin de ligne",
        "L'audit qualité des fournisseurs",
        "La retouche des produits avant expédition",
        "Le traitement des retours sous garantie",
        "La formation des opérateurs au contrôle"],
    a: 3,
    e: "Échec externe = défaut découvert après livraison au client (garanties, retours, réclamations). Tri et retouche sont des échecs internes ; audit et formation sont prévention/évaluation." },

  { phase: "Define",
    q: "Quel élément ne fait normalement PAS partie d'une charte de projet Six Sigma ?",
    o: ["L'énoncé du problème", "L'énoncé de l'objectif", "Le plan de contrôle détaillé", "Le périmètre du projet"],
    a: 2,
    e: "Le plan de contrôle est un livrable de la phase Control. La charte contient : business case, problème, objectif, périmètre, équipe, jalons." },

  { phase: "Define",
    q: "Que signifie l'acronyme SIPOC ?",
    o: ["Suppliers, Inputs, Process, Outputs, Customers",
        "Scope, Issues, Plan, Objectives, Controls",
        "Standard, Inspection, Process, Output, Capability",
        "Sponsors, Investment, Priorities, Owners, Costs"],
    a: 0,
    e: "SIPOC est une cartographie de haut niveau : Fournisseurs, Entrées, Processus (5 à 7 étapes), Sorties, Clients. Elle sert à cadrer le périmètre en Define." },

  { phase: "Define",
    q: "Dans le modèle de Kano, une caractéristique dont l'absence crée une forte insatisfaction mais dont la présence n'augmente pas la satisfaction est dite :",
    o: ["Attractive (excitement)", "De performance (one-dimensional)", "De base (must-be)", "Indifférente"],
    a: 2,
    e: "Les attributs de base sont attendus implicitement : leur absence déçoit, leur présence est « normale ». Ex. : des freins qui fonctionnent sur une voiture." },

  { phase: "Define",
    q: "Dans le modèle de Kano, comment évolue dans le temps une caractéristique « attractive » (enchantement) ?",
    o: ["Elle reste attractive indéfiniment",
        "Elle tend à devenir de performance puis de base",
        "Elle devient indifférente",
        "Elle devient inverse (rejetée par le client)"],
    a: 1,
    e: "Les attentes des clients évoluent : ce qui enchante aujourd'hui (ex. Wi-Fi dans un hôtel) devient exigé demain. D'où la nécessité de réécouter régulièrement la VOC." },

  { phase: "Define",
    q: "Quel rôle Six Sigma est responsable de lever les obstacles, d'allouer les ressources et de valider les tollgates du projet ?",
    o: ["Le Green Belt", "Le Master Black Belt", "Le Champion / Sponsor", "Le Process Owner"],
    a: 2,
    e: "Le Champion (ou Sponsor) est un dirigeant qui parraine le projet, fournit les ressources et lève les blocages. Le MBB coache et forme ; le Process Owner reçoit le processus amélioré." },

  { phase: "Define",
    q: "Quel rôle assure le coaching technique et statistique des Black Belts et Green Belts et pilote le déploiement Six Sigma ?",
    o: ["Le Champion", "Le Master Black Belt", "Le Yellow Belt", "Le Process Owner"],
    a: 1,
    e: "Le Master Black Belt est l'expert méthodologique : formation, mentorat, sélection des projets et cohérence du déploiement." },

  { phase: "Define",
    q: "Parmi les 8 gaspillages du Lean (DOWNTIME), lequel est souvent considéré comme le pire car il génère tous les autres ?",
    o: ["Les attentes", "La surproduction", "Les transports", "Les défauts"],
    a: 1,
    e: "La surproduction crée des stocks, des transports, des attentes, des mouvements et masque les défauts. Elle est la « mère » des gaspillages selon Ohno." },

  { phase: "Define",
    q: "Que représente le « N » dans l'acronyme DOWNTIME des 8 gaspillages ?",
    o: ["Non-conformité", "Non-utilisation des talents", "Nettoyage", "Négociation"],
    a: 1,
    e: "DOWNTIME : Defects, Overproduction, Waiting, Non-utilized talent, Transportation, Inventory, Motion, Extra-processing. Le 8ᵉ gaspillage est le talent inexploité." },

  { phase: "Define",
    q: "Un opérateur doit se pencher et se retourner à chaque cycle pour attraper des composants situés derrière lui. De quel gaspillage s'agit-il ?",
    o: ["Transport", "Mouvement", "Attente", "Sur-traitement"],
    a: 1,
    e: "Le mouvement (Motion) concerne les déplacements inutiles des personnes ; le transport concerne le déplacement des matières et produits." },

  { phase: "Define",
    q: "Polir une face de pièce qui ne sera jamais visible par le client relève de quel gaspillage ?",
    o: ["Sur-traitement (extra-processing)", "Surproduction", "Défaut", "Stock"],
    a: 0,
    e: "Le sur-traitement consiste à faire plus (ou mieux) que ce que le client exige et paie : finitions inutiles, tolérances trop serrées, approbations multiples." },

  { phase: "Define",
    q: "Quels sont, dans l'ordre, les cinq principes du Lean selon Womack et Jones ?",
    o: ["Valeur, Chaîne de valeur, Flux, Tiré, Perfection",
        "Trier, Ranger, Nettoyer, Standardiser, Maintenir",
        "Définir, Mesurer, Analyser, Innover, Contrôler",
        "Planifier, Faire, Vérifier, Agir, Standardiser"],
    a: 0,
    e: "Les 5 principes Lean : spécifier la valeur, identifier la chaîne de valeur, créer le flux, tirer par la demande, viser la perfection. B correspond aux 5S." },

  { phase: "Define",
    q: "Une activité est à valeur ajoutée (VA) si elle satisfait trois critères. Lequel n'en fait PAS partie ?",
    o: ["Le client est prêt à la payer",
        "Elle transforme physiquement ou informationnellement le produit",
        "Elle est réalisée correctement du premier coup",
        "Elle est réalisée par un opérateur qualifié"],
    a: 3,
    e: "Les trois critères de la VA : le client la paie, elle transforme le produit/service, elle est faite bien du premier coup. La qualification de l'opérateur n'entre pas dans la définition." },

  { phase: "Define",
    q: "Un processus a un lead time de 10 jours et un temps à valeur ajoutée total de 4 heures. Quelle est son efficacité du cycle de processus (PCE) ? (journée de 8 h)",
    o: ["5 %", "40 %", "2,5 %", "10 %"],
    a: 0,
    e: "PCE = temps VA / lead time = 4 h / (10 × 8 h) = 4 / 80 = 5 %. Un PCE typique en process non-Lean est < 10 %." },

  { phase: "Define",
    q: "Selon la loi de Little, si un processus contient en moyenne 200 dossiers en cours (WIP) et traite 50 dossiers par jour, quel est le lead time moyen ?",
    o: ["0,25 jour", "4 jours", "250 jours", "10 000 jours"],
    a: 1,
    e: "Loi de Little : Lead time = WIP / Débit = 200 / 50 = 4 jours. Réduire le WIP réduit directement le délai." },

  { phase: "Define",
    q: "Quel énoncé d'objectif (Goal Statement) respecte le mieux les critères SMART ?",
    o: ["Réduire significativement les délais de livraison",
        "Améliorer la qualité du service client d'ici la fin de l'année",
        "Réduire le délai moyen de livraison de 6 à 3 jours d'ici le 30 juin",
        "Devenir le leader du marché en satisfaction client"],
    a: 2,
    e: "SMART : Spécifique, Mesurable, Atteignable, Réaliste, Temporel. Seul C indique une métrique, une baseline, une cible et une échéance." },

  { phase: "Define",
    q: "L'équipe projet réalise un diagramme d'affinités après une session de recueil de la VOC. Quel est le but de cet outil ?",
    o: ["Hiérarchiser les causes racines par importance",
        "Regrouper un grand nombre de verbatims en thèmes naturels",
        "Mesurer la corrélation entre deux variables",
        "Représenter les étapes du processus"],
    a: 1,
    e: "Le diagramme d'affinités (KJ) organise des données verbales nombreuses en catégories cohérentes, étape clé pour passer de la VOC brute aux besoins puis aux CTQ." },

  { phase: "Define",
    q: "Quel outil permet de traduire les besoins clients (« quoi ») en caractéristiques techniques (« comment ») et de les prioriser via une matrice de relations ?",
    o: ["Le SIPOC", "La maison de la qualité (QFD)", "Le diagramme d'Ishikawa", "L'AMDEC"],
    a: 1,
    e: "Le QFD (Quality Function Deployment) ou « maison de la qualité » relie les exigences clients aux caractéristiques de conception et pondère leur importance." },

  { phase: "Define",
    q: "Quelle est la source la plus fiable pour recueillir la voix du client sur un problème existant ?",
    o: ["L'opinion du chef de projet",
        "Les réclamations, enquêtes, entretiens et observation directe du client",
        "Les objectifs financiers de la direction",
        "Les spécifications du bureau d'études"],
    a: 1,
    e: "La VOC se recueille directement auprès des clients : réclamations, enquêtes, focus groups, entretiens, observation. Les autres options sont des voix internes (VOB, VOP)." },

  { phase: "Define",
    q: "Dans une matrice RACI, que désigne la lettre « A » ?",
    o: ["Assistant", "Accountable (redevable / approbateur)", "Advisor", "Analyst"],
    a: 1,
    e: "RACI : Responsible (fait), Accountable (répond du résultat, une seule personne), Consulted (consulté), Informed (informé)." },

  { phase: "Define",
    q: "Une équipe projet traverse une phase de conflits sur les rôles et les méthodes de travail. Selon Tuckman, à quel stade se trouve-t-elle ?",
    o: ["Forming", "Storming", "Norming", "Performing"],
    a: 1,
    e: "Stades de Tuckman : Forming (formation), Storming (tensions), Norming (normalisation), Performing (performance), puis Adjourning (dissolution)." },

  { phase: "Define",
    q: "Le périmètre d'un projet s'élargit progressivement sans validation formelle. Comment nomme-t-on ce phénomène ?",
    o: ["Scope creep (dérive du périmètre)", "Gold plating", "Benchmarking", "Tollgate"],
    a: 0,
    e: "Le scope creep est l'extension non maîtrisée du périmètre. La charte et le SIPOC servent justement à fixer les frontières « dedans / dehors » du projet." },

  { phase: "Define",
    q: "Quelle est la principale différence entre DMAIC et DMADV (DFSS) ?",
    o: ["DMAIC est réservé aux services, DMADV à l'industrie",
        "DMAIC améliore un processus existant, DMADV conçoit un nouveau produit/processus",
        "DMADV ne nécessite pas de données",
        "DMAIC est plus long que DMADV"],
    a: 1,
    e: "DMAIC (Define, Measure, Analyze, Improve, Control) optimise l'existant. DMADV (Define, Measure, Analyze, Design, Verify) relève du Design for Six Sigma pour créer du neuf." },

  { phase: "Define",
    q: "Quelle relation fondamentale résume la philosophie Six Sigma ?",
    o: ["Y = f(x)", "σ = √variance", "Cp = Cpk", "Coût = Prix − Marge"],
    a: 0,
    e: "Y = f(x) : la sortie (Y, CTQ) est fonction des entrées et paramètres du processus (x). Six Sigma cherche les x vitaux qui pilotent Y." },

  { phase: "Define",
    q: "Un « tollgate » (revue de jalon) en fin de phase Define sert principalement à :",
    o: ["Former les opérateurs aux nouveaux standards",
        "Valider avec le Champion les livrables de la phase avant de passer à la suivante",
        "Calculer la capabilité du processus",
        "Clôturer définitivement le projet"],
    a: 1,
    e: "Le tollgate est une revue formelle : charte, VOC/CTQ, SIPOC, équipe et plan sont validés par le Sponsor avant d'engager la phase Measure." },

  { phase: "Define",
    q: "Quel critère est le plus pertinent pour sélectionner un projet Six Sigma ?",
    o: ["La solution est déjà connue et il suffit de la déployer",
        "Le problème est lié à un CTQ, chronique, mesurable, avec un impact financier significatif",
        "Le projet concerne un processus qui va être supprimé dans 6 mois",
        "Le problème est ponctuel et n'est apparu qu'une seule fois"],
    a: 1,
    e: "Un bon projet DMAIC traite un problème chronique aux causes inconnues, mesurable, aligné sur la stratégie et l'impact client/financier. Solution connue → « just do it »." },

  { phase: "Define",
    q: "Quel est le rôle du Process Owner dans un projet Six Sigma ?",
    o: ["Il réalise l'analyse statistique",
        "Il finance le programme Six Sigma de l'entreprise",
        "Il est responsable du processus au quotidien et pérennise les améliorations après le projet",
        "Il forme les Black Belts"],
    a: 2,
    e: "Le Process Owner (propriétaire du processus) est le destinataire final : il doit adhérer aux changements et maintenir le plan de contrôle après la clôture." },

  { phase: "Define",
    q: "Quelle est la différence entre le temps de cycle et le lead time ?",
    o: ["Ce sont deux termes synonymes",
        "Le temps de cycle est le temps entre deux sorties consécutives ; le lead time est le délai total de traversée d'une unité",
        "Le lead time ne concerne que les services",
        "Le temps de cycle inclut les attentes, pas le lead time"],
    a: 1,
    e: "Lead time = délai de bout en bout (incluant attentes). Temps de cycle = cadence de sortie d'une étape ou du processus. Ils sont liés par la loi de Little." },

  { phase: "Define",
    q: "Dans un business case, l'équipe estime que le problème coûte 250 k€/an et que le projet vise à récupérer 60 % de ce montant. Quel est le gain annuel attendu ?",
    o: ["100 k€", "150 k€", "250 k€", "60 k€"],
    a: 1,
    e: "250 k€ × 0,60 = 150 k€. Le business case chiffre l'enjeu financier pour justifier l'allocation de ressources." },

  { phase: "Define",
    q: "Quel outil visualise l'ensemble du flux de matières et d'informations, du fournisseur au client, avec les temps VA et NVA ?",
    o: ["Le diagramme spaghetti", "La cartographie de la chaîne de valeur (VSM)", "Le SIPOC", "Le diagramme de Gantt"],
    a: 1,
    e: "La VSM (Value Stream Map) montre étapes, stocks, flux d'information, temps de cycle et lead time, et met en évidence le ratio VA/NVA." },

  { phase: "Define",
    q: "Quel outil trace les déplacements physiques d'un opérateur ou d'un produit sur un plan d'atelier ?",
    o: ["Le diagramme spaghetti", "Le diagramme de Pareto", "Le diagramme d'Ishikawa", "La matrice de priorisation"],
    a: 0,
    e: "Le diagramme spaghetti révèle les gaspillages de mouvement et de transport en traçant les trajets réels sur un layout." },

  { phase: "Define",
    q: "Dans le Lean, que désignent les 3 M : Muda, Mura, Muri ?",
    o: ["Gaspillage, Irrégularité, Surcharge", "Machine, Matière, Méthode", "Mesure, Moyenne, Médiane", "Marché, Marge, Mission"],
    a: 0,
    e: "Muda = gaspillage, Mura = variabilité/irrégularité, Muri = surcharge (des hommes ou machines). Mura et Muri génèrent souvent du Muda." },

  { phase: "Define",
    q: "Quelle démarche consiste à aller observer le processus réel sur le terrain plutôt que de se fier aux rapports ?",
    o: ["Hoshin Kanri", "Gemba walk", "Poka-yoke", "Heijunka"],
    a: 1,
    e: "Le Gemba (« lieu réel ») : aller voir, comprendre et poser des questions là où la valeur est créée. Principe fondamental du Lean management." },

  { phase: "Define",
    q: "Quelle voix représente les contraintes et exigences internes de l'entreprise (rentabilité, stratégie, réglementation) ?",
    o: ["VOC — Voice of the Customer", "VOP — Voice of the Process", "VOB — Voice of the Business", "VOE — Voice of the Employee"],
    a: 2,
    e: "VOB = exigences de l'entreprise ; VOC = besoins clients ; VOP = ce que le processus produit réellement (données) ; VOE = les employés." },

  { phase: "Define",
    q: "Un projet vise à réduire les délais de facturation. Quelle partie prenante est un client « interne » du processus ?",
    o: ["Le patient qui reçoit la facture", "Le service recouvrement qui utilise les factures émises", "L'autorité fiscale", "Le fournisseur de papier"],
    a: 1,
    e: "Le client interne est le service en aval qui reçoit la sortie du processus. Les clients externes sont hors de l'organisation." },

  { phase: "Define",
    q: "Une entreprise parle de « qualité 6 sigma ». Cela correspond à quel niveau de défauts à long terme ?",
    o: ["3,4 défauts par million d'opportunités", "233 DPMO", "6 210 DPMO", "0,002 DPMO"],
    a: 0,
    e: "6σ = 3,4 DPMO en intégrant le décalage de 1,5σ. Sans décalage, ce serait 0,002 DPMO (2 par milliard). 5σ = 233, 4σ = 6 210." },

  { phase: "Define",
    q: "Dans un projet Lean, un système où l'étape amont ne produit que lorsque l'étape aval consomme est appelé :",
    o: ["Flux poussé", "Flux tiré", "Production par lots", "Flux MRP"],
    a: 1,
    e: "Le flux tiré (pull) déclenche la production par la demande réelle aval (kanban), limitant surproduction et stocks. Le flux poussé produit selon prévision." },

  { phase: "Define",
    q: "Quel élément d'une charte de projet définit les frontières du processus étudié (début, fin, inclusions, exclusions) ?",
    o: ["Le business case", "Le périmètre (scope)", "Le plan de communication", "L'énoncé de l'objectif"],
    a: 1,
    e: "Le périmètre délimite ce qui est dans et hors du projet. Il est appuyé par le SIPOC et évite le scope creep." },

  { phase: "Define",
    q: "Quelle méthode Lean vise à niveler la production en volume et en mix pour réduire le Mura ?",
    o: ["Heijunka", "Jidoka", "Andon", "Kaizen"],
    a: 0,
    e: "Heijunka = lissage de la production. Jidoka = autonomation (arrêt automatique sur défaut), Andon = signal visuel d'alerte, Kaizen = amélioration continue." },

  { phase: "Define",
    q: "Un analyste calcule le coût des inspections systématiques en fin de ligne. Dans quelle catégorie du COPQ se classe ce coût ?",
    o: ["Coût de prévention", "Coût d'évaluation (détection)", "Échec interne", "Échec externe"],
    a: 1,
    e: "Les coûts d'évaluation couvrent les inspections, tests et audits destinés à détecter les défauts. La prévention vise à les éviter (formation, AMDEC, poka-yoke)." },

  { phase: "Define",
    q: "Lequel de ces éléments est un coût de prévention dans le modèle COPQ ?",
    o: ["Les rebuts", "Les rappels produits", "La formation qualité et la revue de conception", "Le contrôle réception"],
    a: 2,
    e: "Prévention = actions en amont pour éviter les défauts : formation, planification qualité, revues de conception, maîtrise fournisseurs." },

  { phase: "Define",
    q: "Lors du cadrage, l'équipe utilise un diagramme de Pareto des réclamations. Quel principe sous-tend cet outil ?",
    o: ["50 % des causes produisent 50 % des effets",
        "Environ 80 % des effets proviennent d'environ 20 % des causes",
        "Toutes les causes ont un poids équivalent",
        "Les causes rares sont les plus coûteuses"],
    a: 1,
    e: "Principe de Pareto (80/20) : concentrer les efforts sur les « quelques causes vitales » plutôt que les « nombreuses causes triviales »." },

  { phase: "Define",
    q: "Quelle affirmation décrit le mieux un « Quick Win » identifié en phase Define ?",
    o: ["Une amélioration nécessitant une analyse statistique poussée",
        "Une action simple, à faible risque et faible coût, déployable immédiatement sans attendre la fin du DMAIC",
        "Un objectif financier à 3 ans",
        "Une modification majeure du périmètre"],
    a: 1,
    e: "Les quick wins sont des gains rapides évidents ; ils motivent l'équipe mais ne dispensent pas de la démarche DMAIC pour les causes complexes." },

  { phase: "Define",
    q: "Une organisation veut aligner les objectifs stratégiques de la direction avec les projets opérationnels à tous les niveaux. Quelle méthode utilise-t-elle ?",
    o: ["Hoshin Kanri (déploiement de politique)", "5S", "SMED", "Diagramme spaghetti"],
    a: 0,
    e: "Hoshin Kanri décline la stratégie en objectifs et projets cohérents (matrice en X), assurant que les projets Six Sigma servent la vision." },

  { phase: "Define",
    q: "Un processus produit 40 unités/heure alors que le takt time est de 2 minutes. Quelle conclusion tirer ?",
    o: ["Le processus est plus lent que la demande",
        "Le processus est exactement au takt",
        "Le processus est plus rapide que la demande, risque de surproduction",
        "Impossible à déterminer"],
    a: 2,
    e: "Takt de 2 min = 30 unités/heure demandées. Produire 40/h dépasse la demande → surproduction et stocks si non régulé." },

  { phase: "Define",
    q: "Quelle affirmation sur le Kaizen est correcte ?",
    o: ["C'est une refonte radicale et ponctuelle du processus",
        "C'est une démarche d'amélioration continue par petits pas impliquant tous les employés",
        "Il ne s'applique qu'aux fonctions support",
        "Il remplace le DMAIC"],
    a: 1,
    e: "Kaizen = « changement pour le meilleur » : améliorations incrémentales et continues par les équipes terrain. La refonte radicale est le Kaikaku." }
];
