// Phase IMPROVE — 40 questions
const IMPROVE_QUESTIONS = [
  { phase: "Improve",
    q: "Une régression linéaire simple donne un R² = 0,64. Quelle est l'interprétation correcte ?",
    o: ["64 % de la variation de Y est expliquée par X", "La corrélation entre X et Y est de 0,64", "64 % des prédictions du modèle sont correctes", "X cause Y dans 64 % des cas observés"],
    a: 0,
    e: "R² est le coefficient de détermination : part de la variance de Y expliquée par le modèle. r = √0,64 = 0,80. La régression n'établit pas la causalité." },

  { phase: "Improve",
    q: "Dans une régression multiple, un prédicteur X₂ affiche une p-value de 0,42 (α = 0,05). Quelle décision prendre concernant ce terme ?",
    o: ["Le conserver, car sa p-value est supérieure à α", "Le conserver, car tout prédicteur améliore le R²", "Le transformer en logarithme pour le rendre significatif", "L'envisager pour retrait, car il n'est pas significatif"],
    a: 3,
    e: "p = 0,42 > 0,05 : le coefficient de X₂ n'est pas significativement différent de zéro. On simplifie le modèle en le retirant (en vérifiant le R² ajusté)." },

  { phase: "Improve",
    q: "L'équation de régression obtenue est Y = 12 + 3,5 X. Que représente le coefficient 3,5 ?",
    o: ["La valeur de Y lorsque X vaut zéro", "La variation de Y pour une augmentation d'une unité de X", "Le coefficient de corrélation entre X et Y", "L'erreur-type de l'estimation de Y"],
    a: 1,
    e: "3,5 est la pente ; 12 est l'ordonnée à l'origine (valeur de Y quand X = 0)." },

  { phase: "Improve",
    q: "Après une régression, quel graphique permet de vérifier l'hypothèse de variance constante des résidus (homoscédasticité) ?",
    o: ["Droite de Henry des résidus", "Résidus en fonction des valeurs ajustées", "Histogramme des résidus", "Résidus en fonction de l'ordre d'observation"],
    a: 1,
    e: "Résidus vs valeurs ajustées : une dispersion en « entonnoir » signale une variance non constante." },

  { phase: "Improve",
    q: "Pourquoi préfère-t-on le R² ajusté au R² pour comparer des modèles de régression multiple ?",
    o: ["Il est toujours plus grand", "Il pénalise l'ajout de prédicteurs inutiles, alors que le R² augmente mécaniquement avec chaque terme ajouté", "Il mesure la corrélation", "Il ne dépend pas des données"],
    a: 1,
    e: "R² ajusté = 1 − (1 − R²)(n − 1)/(n − p − 1). Il diminue si un terme ajouté n'apporte pas assez d'explication." },

  { phase: "Improve",
    q: "Dans une régression multiple, deux prédicteurs sont fortement corrélés entre eux (VIF = 12). Quel problème cela pose-t-il ?",
    o: ["Aucun", "Multicolinéarité : coefficients instables et difficiles à interpréter", "Le R² devient négatif", "Les résidus deviennent non normaux"],
    a: 1,
    e: "VIF > 5–10 signale une multicolinéarité forte. Solution : retirer un des prédicteurs ou les combiner." },

  { phase: "Improve",
    q: "Un plan factoriel complet à 2 niveaux avec 4 facteurs comporte combien d'essais (sans réplication) ?",
    o: ["8", "16", "32", "4"],
    a: 1,
    e: "2^k = 2⁴ = 16 essais. Avec 2 réplications : 32 essais." },

  { phase: "Improve",
    q: "Un plan 2⁵⁻¹ comporte combien d'essais et de quelle fraction s'agit-il ?",
    o: ["32 essais, plan complet", "16 essais, demi-fraction", "8 essais, quart de fraction", "5 essais"],
    a: 1,
    e: "2⁵⁻¹ = 2⁴ = 16 essais, soit la moitié des 32 du plan complet. Le prix : certains effets sont confondus (aliasés)." },

  { phase: "Improve",
    q: "Dans un plan fractionnaire de résolution III :",
    o: ["Les effets principaux sont confondus avec des interactions à 2 facteurs", "Les effets principaux sont confondus avec des interactions à 3 facteurs", "Aucun effet n'est confondu", "Les interactions à 2 facteurs sont confondues entre elles uniquement"],
    a: 0,
    e: "Résolution III : principaux ⇔ interactions d'ordre 2 (risqué). Résolution IV : principaux ⇔ interactions d'ordre 3, et ordre 2 ⇔ ordre 2. Résolution V : principaux ⇔ ordre 4, ordre 2 ⇔ ordre 3." },

  { phase: "Improve",
    q: "Dans un plan de résolution IV, les effets principaux sont confondus avec :",
    o: ["D'autres effets principaux", "Des interactions à 2 facteurs", "Des interactions à 3 facteurs", "Rien"],
    a: 2,
    e: "Résolution IV : effets principaux clairs des interactions d'ordre 2, mais les interactions d'ordre 2 sont confondues entre elles." },

  { phase: "Improve",
    q: "Qu'est-ce qu'une interaction entre deux facteurs dans un DOE ?",
    o: ["Les deux facteurs sont corrélés", "L'effet d'un facteur sur la réponse dépend du niveau de l'autre facteur", "Les deux facteurs ont le même effet", "Les facteurs sont confondus"],
    a: 1,
    e: "Sur un graphique d'interaction, des lignes non parallèles (qui se croisent) signalent une interaction. Les plans un-facteur-à-la-fois (OFAT) ne peuvent pas la détecter." },

  { phase: "Improve",
    q: "Quel est le principal inconvénient de l'approche « un facteur à la fois » (OFAT) par rapport au plan d'expériences ?",
    o: ["Elle demande moins d'essais", "Elle ne détecte pas les interactions et nécessite plus d'essais pour la même précision", "Elle est plus statistique", "Elle nécessite un logiciel"],
    a: 1,
    e: "Le DOE fait varier tous les facteurs simultanément selon une matrice orthogonale : chaque essai informe sur tous les effets, et les interactions sont estimables." },

  { phase: "Improve",
    q: "Pourquoi randomise-t-on l'ordre des essais dans un plan d'expériences ?",
    o: ["Pour réduire le nombre d'essais", "Pour éviter que des facteurs non contrôlés variant dans le temps (dérive, usure) ne se confondent avec les effets étudiés", "Pour augmenter la résolution", "Pour faciliter les changements de réglage"],
    a: 1,
    e: "La randomisation protège contre les biais systématiques liés à l'ordre. La réplication estime l'erreur ; le blocage isole les nuisances connues." },

  { phase: "Improve",
    q: "Une expérience doit se dérouler sur deux lots de matière différents. Quelle technique de DOE permet d'isoler l'effet du lot ?",
    o: ["La randomisation", "Le blocage (blocking)", "La réplication", "L'ajout de points centraux"],
    a: 1,
    e: "Le blocage assigne les essais à des blocs (lots, jours, machines) pour extraire leur variabilité de l'erreur expérimentale." },

  { phase: "Improve",
    q: "À quoi servent les points centraux (center points) dans un plan factoriel à 2 niveaux ?",
    o: ["À réduire le nombre d'essais", "À détecter une courbure (non-linéarité) de la réponse et estimer l'erreur pure", "À augmenter la résolution", "À aliasser les interactions"],
    a: 1,
    e: "Si la moyenne des points centraux diffère significativement de la moyenne des points factoriels, la relation n'est pas linéaire → plan de surface de réponse." },

  { phase: "Improve",
    q: "Qu'est-ce que la réplication dans un DOE ?",
    o: ["Mesurer plusieurs fois la même pièce", "Refaire l'intégralité d'une condition expérimentale (nouveau réglage, nouvelle pièce) pour estimer l'erreur expérimentale", "Copier la matrice d'essais", "Répéter uniquement le point central"],
    a: 1,
    e: "Réplication ≠ répétition de mesure. La vraie réplication inclut toute la variabilité du re-réglage et permet de tester la significativité des effets." },

  { phase: "Improve",
    q: "Dans un plan 2², l'effet principal du facteur A est calculé comme :",
    o: ["La moyenne de toutes les réponses", "La moyenne des réponses à A haut moins la moyenne des réponses à A bas", "Le produit des réponses", "La différence entre max et min"],
    a: 1,
    e: "Effet A = ȳ(A+) − ȳ(A−). Le coefficient du modèle codé vaut la moitié de l'effet." },

  { phase: "Improve",
    q: "Un plan 2² donne : (A−,B−)=10 ; (A+,B−)=20 ; (A−,B+)=12 ; (A+,B+)=30. Quel est l'effet principal de A ?",
    o: ["10", "14", "8", "18"],
    a: 1,
    e: "Effet A = (20 + 30)/2 − (10 + 12)/2 = 25 − 11 = 14. Effet B = (12+30)/2 − (10+20)/2 = 6. Interaction AB = (10+30)/2 − (20+12)/2 = 4." },

  { phase: "Improve",
    q: "Dans un plan factoriel, un diagramme de Pareto des effets standardisés montre une ligne de référence. Que représente-t-elle ?",
    o: ["La moyenne des effets", "Le seuil de significativité (valeur t critique à α)", "Le plus grand effet", "Le R²"],
    a: 1,
    e: "Les effets dont la barre dépasse la ligne sont statistiquement significatifs au niveau α choisi." },

  { phase: "Improve",
    q: "Un plan de criblage (screening) est utilisé pour :",
    o: ["Optimiser finement 2 facteurs", "Identifier rapidement, parmi de nombreux facteurs, ceux qui ont un effet réel", "Valider le plan de contrôle", "Mesurer la répétabilité"],
    a: 1,
    e: "Plans fractionnaires ou Plackett-Burman : peu d'essais, beaucoup de facteurs. On approfondit ensuite les quelques facteurs significatifs." },

  { phase: "Improve",
    q: "Après avoir identifié les facteurs significatifs, quelle méthode permet de trouver les réglages optimaux en présence de courbure ?",
    o: ["Plan de Plackett-Burman", "Méthodologie de surface de réponse (RSM : plan composite centré, Box-Behnken)", "Test t", "Diagramme d'Ishikawa"],
    a: 1,
    e: "La RSM ajuste un modèle quadratique pour localiser l'optimum (maximum, minimum ou cible)." },

  { phase: "Improve",
    q: "Qu'est-ce que le codage des facteurs (−1 / +1) dans un DOE ?",
    o: ["Une convention pour rendre les effets comparables et la matrice orthogonale, indépendamment des unités", "Une erreur de saisie", "Le nombre de réplications", "La résolution du plan"],
    a: 0,
    e: "En unités codées, le niveau bas vaut −1 et le haut +1 ; les coefficients sont directement comparables entre facteurs." },

  { phase: "Improve",
    q: "Un poka-yoke est :",
    o: ["Un outil de statistique descriptive", "Un dispositif anti-erreur qui rend l'erreur impossible ou la détecte immédiatement", "Une technique de brainstorming", "Un graphique de contrôle"],
    a: 1,
    e: "Exemples : détrompeur mécanique, connecteur asymétrique, capteur bloquant le cycle. Le poka-yoke de prévention est supérieur à celui de détection." },

  { phase: "Improve",
    q: "Une prise USB-C ne peut être insérée que dans un sens et fonctionne dans les deux. De quel type de solution s'agit-il ?",
    o: ["Poka-yoke de prévention (élimine l'erreur à la source)", "Poka-yoke de détection", "SMED", "Kanban"],
    a: 0,
    e: "La conception rend l'erreur impossible : c'est le niveau le plus élevé de mistake-proofing." },

  { phase: "Improve",
    q: "Quelle méthode Lean vise à réduire les temps de changement de série ?",
    o: ["5S", "SMED (Single-Minute Exchange of Die)", "Kanban", "Andon"],
    a: 1,
    e: "SMED : séparer opérations internes (machine arrêtée) et externes (machine en marche), convertir l'interne en externe, rationaliser le reste." },

  { phase: "Improve",
    q: "Dans la méthode SMED, une opération « interne » est :",
    o: ["Réalisée par le personnel interne", "Réalisée obligatoirement machine arrêtée", "Réalisée pendant que la machine produit", "Une opération de maintenance"],
    a: 1,
    e: "L'objectif est de convertir un maximum d'opérations internes (machine arrêtée) en externes (préparation en temps masqué)." },

  { phase: "Improve",
    q: "Quelles sont les cinq étapes des 5S dans l'ordre ?",
    o: ["Seiri (trier), Seiton (ranger), Seiso (nettoyer), Seiketsu (standardiser), Shitsuke (maintenir)", "Standardiser, Trier, Nettoyer, Ranger, Maintenir", "Sécuriser, Simplifier, Superviser, Signaler, Suivre", "Sélectionner, Séparer, Stocker, Sceller, Signer"],
    a: 0,
    e: "5S : débarrasser, ranger (une place pour chaque chose), nettoyer/inspecter, standardiser, respecter/pérenniser. Certains ajoutent Sécurité (6S)." },

  { phase: "Improve",
    q: "Une équipe a généré 25 idées de solutions. Quel outil permet de les comparer objectivement contre des critères pondérés (coût, impact, faisabilité) ?",
    o: ["Diagramme d'Ishikawa", "Matrice de sélection (Pugh ou matrice de priorisation pondérée)", "Carte X̄-R", "SIPOC"],
    a: 1,
    e: "La matrice de Pugh compare chaque solution à une référence sur des critères ; la matrice pondérée attribue des scores × poids." },

  { phase: "Improve",
    q: "Pourquoi réaliser un pilote avant le déploiement complet d'une solution ?",
    o: ["Pour retarder le projet", "Pour valider l'efficacité réelle, détecter les effets secondaires et ajuster à faible risque", "Pour éviter le plan de contrôle", "Ce n'est jamais utile"],
    a: 1,
    e: "Le pilote (périmètre limité) confirme le lien X→Y en conditions réelles et prépare le déploiement (formation, documentation)." },

  { phase: "Improve",
    q: "Après implémentation d'une solution, l'équipe met à jour l'AMDEC processus. Pourquoi ?",
    o: ["Pour justifier le budget", "Pour réévaluer les risques (nouveaux modes de défaillance, RPN réduits) du processus modifié", "Parce que l'AMDEC initiale était fausse", "Pour remplacer le plan de contrôle"],
    a: 1,
    e: "Toute modification de processus crée potentiellement de nouveaux risques ; l'AMDEC vivante sert aussi de base au plan de contrôle." },

  { phase: "Improve",
    q: "Quelle technique de créativité impose de suspendre tout jugement pendant la génération d'idées ?",
    o: ["Le brainstorming", "L'analyse de régression", "L'AMDEC", "Le test t"],
    a: 0,
    e: "Règles du brainstorming : pas de critique, quantité avant qualité, rebondir sur les idées, encourager les idées farfelues. L'évaluation vient après." },

  { phase: "Improve",
    q: "Une analyse coûts-bénéfices montre un investissement de 40 k€ pour un gain annuel de 100 k€. Quel est le retour sur investissement simple (délai de récupération) ?",
    o: ["2,5 ans", "0,4 an (≈ 5 mois)", "4 ans", "1 an"],
    a: 1,
    e: "Payback = investissement / gain annuel = 40/100 = 0,4 an ≈ 4,8 mois. Le ROI = (100 − 40)/40 = 150 % la première année." },

  { phase: "Improve",
    q: "Dans un DOE, deux effets sont « aliasés » (confondus). Cela signifie que :",
    o: ["Ils sont égaux à zéro", "Le plan ne permet pas de distinguer leur contribution : on estime leur somme", "Ils sont indépendants", "Ils ont été randomisés"],
    a: 1,
    e: "L'aliasing est le prix des plans fractionnaires. On lève l'ambiguïté par un « fold-over » ou en supposant les interactions d'ordre élevé négligeables." },

  { phase: "Improve",
    q: "Une réponse Y doit être maximisée. Le DOE montre A significatif avec effet +8 et B significatif avec effet −5, sans interaction. Quels réglages choisir ?",
    o: ["A bas, B bas", "A haut, B bas", "A haut, B haut", "A bas, B haut"],
    a: 1,
    e: "Effet positif → niveau haut augmente Y ; effet négatif → niveau bas augmente Y. Sans interaction, on choisit les niveaux indépendamment." },

  { phase: "Improve",
    q: "Une régression multiple donne Y = 20 + 4X₁ − 2X₂ avec R² ajusté = 0,85. Que prédit-on pour X₁ = 5, X₂ = 10 ?",
    o: ["20", "40", "60", "0"],
    a: 0,
    e: "Y = 20 + 4×5 − 2×10 = 20 + 20 − 20 = 20." },

  { phase: "Improve",
    q: "Un plan Plackett-Burman à 12 essais permet de cribler jusqu'à combien de facteurs ?",
    o: ["4", "11", "12", "24"],
    a: 1,
    e: "Plackett-Burman à N essais cribler jusqu'à N − 1 facteurs (résolution III, effets principaux uniquement)." },

  { phase: "Improve",
    q: "Le graphique d'interaction A×B montre deux lignes parfaitement parallèles. Conclusion ?",
    a: 0,
    o: ["Pas d'interaction : l'effet de A est le même quel que soit le niveau de B", "Interaction forte", "A n'a pas d'effet", "B n'a pas d'effet"],
    e: "Parallélisme = additivité des effets. Des lignes qui se croisent ou divergent signalent une interaction." },

  { phase: "Improve",
    q: "Qu'est-ce que la « cellule en U » dans l'amélioration Lean d'un flux ?",
    o: ["Un stockage tampon", "Un agencement des postes en U permettant à un opérateur de suivre le flux avec des déplacements minimaux et une flexibilité de staffing", "Un type de carte de contrôle", "Une matrice de sélection"],
    a: 1,
    e: "La cellule en U rapproche entrée et sortie, favorise le flux pièce à pièce et l'équilibrage des postes selon le takt." },

  { phase: "Improve",
    q: "Quelle affirmation décrit le mieux le kanban ?",
    o: ["Un système de planification poussée par prévision", "Un signal visuel qui autorise la production ou le réapprovisionnement en fonction de la consommation réelle (flux tiré)", "Une carte de contrôle pour attributs", "Un test statistique"],
    a: 1,
    e: "Le kanban limite l'en-cours (WIP) et synchronise la production sur la demande aval." },

  { phase: "Improve",
    q: "L'équipe hésite entre deux solutions techniquement équivalentes. L'une est simple et réversible, l'autre complexe et coûteuse. Quel principe guide le choix ?",
    o: ["Choisir la plus complexe pour impressionner la direction", "Privilégier la solution la plus simple, robuste et facile à maintenir (à efficacité égale)", "Reporter la décision indéfiniment", "Choisir au hasard"],
    a: 1,
    e: "Simplicité = moins de risques de mise en œuvre, adoption plus facile, coût de contrôle plus faible." }
];
