// Phase MEASURE — partie 2 (55 questions)
const MEASURE_QUESTIONS_2 = [
  { phase: "Measure",
    q: "Une entreprise tire au sort un dossier toutes les 20 positions dans une file classée chronologiquement. De quelle méthode d'échantillonnage s'agit-il ?",
    o: ["Aléatoire simple", "Stratifié", "Systématique", "Par grappes"],
    a: 2,
    e: "L'échantillonnage systématique prélève à intervalle fixe. Risque : si une périodicité du processus coïncide avec l'intervalle, l'échantillon est biaisé." },

  { phase: "Measure",
    q: "Pour garantir que chaque équipe (matin, après-midi, nuit) soit représentée proportionnellement dans l'échantillon, quelle méthode utiliser ?",
    o: ["Aléatoire simple", "Stratifié", "Systématique", "De convenance"],
    a: 1,
    e: "L'échantillonnage stratifié divise la population en strates homogènes puis échantillonne dans chacune, garantissant la représentativité des sous-groupes." },

  { phase: "Measure",
    q: "Quel est le principal risque d'un échantillonnage « de convenance » (prendre les pièces les plus accessibles) ?",
    o: ["Un coût trop élevé", "Un biais de sélection rendant l'échantillon non représentatif", "Une taille d'échantillon trop grande", "Une variance nulle"],
    a: 1,
    e: "Sans tirage aléatoire, l'échantillon peut systématiquement différer de la population (ex. pièces du dessus du bac = dernières produites)." },

  { phase: "Measure",
    q: "Une population est finie et un échantillon de chaque unité est tiré de manière à ce que chaque unité ait la même probabilité d'être sélectionnée. C'est un échantillonnage :",
    o: ["Aléatoire simple", "Stratifié", "Systématique", "Par jugement"],
    a: 0,
    e: "L'aléatoire simple donne à chaque unité une probabilité égale et indépendante d'être choisie ; il est la base des inférences statistiques." },

  { phase: "Measure",
    q: "Quel graphique montre la distribution de données continues en barres de fréquence par classes ?",
    o: ["Le diagramme de Pareto", "L'histogramme", "Le run chart", "Le diagramme de dispersion"],
    a: 1,
    e: "L'histogramme révèle la forme (symétrie, bimodalité), le centrage et la dispersion. Le Pareto trie des catégories par fréquence décroissante." },

  { phase: "Measure",
    q: "Un histogramme présente deux pics distincts (bimodal). Quelle est l'interprétation la plus probable ?",
    o: ["Le processus est parfaitement centré", "Deux populations sont mélangées (2 machines, 2 équipes, 2 lots…)", "La loi est exponentielle", "L'instrument est trop précis"],
    a: 1,
    e: "La bimodalité signale la superposition de deux sources différentes. Il faut stratifier les données pour les séparer." },

  { phase: "Measure",
    q: "Dans une boîte à moustaches (box plot), que représente la boîte centrale ?",
    o: ["La moyenne ± 1 écart-type", "L'intervalle interquartile Q1–Q3 contenant 50 % des données", "L'étendue complète", "L'intervalle de confiance de la médiane"],
    a: 1,
    e: "La boîte va du 1er au 3ᵉ quartile (IQR), le trait intérieur est la médiane, les moustaches s'étendent jusqu'à 1,5 IQR ; au-delà, les points sont des outliers." },

  { phase: "Measure",
    q: "Pour des données Q1 = 20 et Q3 = 32, à partir de quelle valeur supérieure un point est-il considéré comme atypique (outlier) sur un box plot ?",
    o: ["32", "44", "50", "38"],
    a: 2,
    e: "IQR = 32 − 20 = 12. Limite supérieure = Q3 + 1,5 × IQR = 32 + 18 = 50. Limite inférieure = 20 − 18 = 2." },

  { phase: "Measure",
    q: "Quel graphique permet de visualiser l'évolution d'une métrique dans le temps sans limites de contrôle statistiques ?",
    o: ["Histogramme", "Run chart (graphique de séquence)", "Box plot", "Diagramme de Pareto"],
    a: 1,
    e: "Le run chart trace les données dans l'ordre chronologique avec la médiane ; il détecte tendances, cycles et décalages avant même une carte de contrôle." },

  { phase: "Measure",
    q: "Quel graphique est utilisé pour étudier la relation entre deux variables continues ?",
    o: ["Le diagramme de dispersion (scatter plot)", "L'histogramme", "Le diagramme de Pareto", "Le diagramme en secteurs"],
    a: 0,
    e: "Le nuage de points visualise la corrélation (sens, force, linéarité) entre X et Y. Il précède le calcul du coefficient de corrélation." },

  { phase: "Measure",
    q: "Un test d'Anderson-Darling donne p = 0,32. Que conclure quant à la normalité des données (α = 0,05) ?",
    o: ["Les données ne sont pas normales", "On ne peut pas rejeter la normalité ; les données peuvent être considérées comme normales", "Le test est invalide", "Il faut transformer les données"],
    a: 1,
    e: "H₀ du test de normalité : les données suivent une loi normale. p = 0,32 > 0,05 → on ne rejette pas H₀." },

  { phase: "Measure",
    q: "Sur une droite de Henry (normal probability plot), comment reconnaît-on des données normales ?",
    o: ["Les points forment une courbe en S", "Les points s'alignent approximativement sur une droite", "Les points forment un nuage sans structure", "Les points forment une parabole"],
    a: 1,
    e: "Si les données sont normales, les quantiles observés vs théoriques s'alignent. Une courbure indique une asymétrie ; un S indique des queues lourdes ou légères." },

  { phase: "Measure",
    q: "Les données de temps de cycle sont fortement asymétriques et non normales. Quelle transformation est fréquemment utilisée pour les normaliser avant une étude de capabilité ?",
    o: ["Transformation de Box-Cox", "Centrage-réduction (z)", "Multiplication par une constante", "Arrondi à l'entier"],
    a: 0,
    e: "Box-Cox (Y^λ) ou Johnson transforment les données pour approcher la normalité. Alternative : ajuster une autre distribution (Weibull, lognormale)." },

  { phase: "Measure",
    q: "Un processus a un kurtosis (aplatissement) très supérieur à celui de la loi normale. Que cela signifie-t-il ?",
    o: ["La distribution est décalée à droite", "La distribution a des queues plus lourdes et un pic plus pointu (leptokurtique)", "La distribution est uniforme", "La moyenne est nulle"],
    a: 1,
    e: "Kurtosis élevé = plus de valeurs extrêmes qu'une normale. L'asymétrie (skewness) décrit le décalage, pas le kurtosis." },

  { phase: "Measure",
    q: "Quelle est la différence entre un paramètre et une statistique ?",
    o: ["Aucune", "Un paramètre décrit la population (μ, σ) ; une statistique décrit l'échantillon (x̄, s)", "Une statistique décrit la population, un paramètre l'échantillon", "Un paramètre est toujours connu"],
    a: 1,
    e: "On utilise les statistiques d'échantillon pour estimer les paramètres inconnus de la population." },

  { phase: "Measure",
    q: "Selon le théorème de la limite centrale, la distribution des moyennes d'échantillons :",
    o: ["Est toujours identique à celle de la population",
        "Tend vers une loi normale quand n augmente, quelle que soit la distribution d'origine",
        "A un écart-type égal à celui de la population",
        "N'existe que pour des populations normales"],
    a: 1,
    e: "TLC : pour n suffisant (≈ 30), les moyennes x̄ suivent une normale de moyenne μ et d'écart-type σ/√n, même si la population ne l'est pas." },

  { phase: "Measure",
    q: "Une entreprise mesure l'OEE (TRS) d'une machine : disponibilité 90 %, performance 95 %, qualité 98 %. Quel est l'OEE ?",
    o: ["94,3 %", "83,8 %", "90,0 %", "283 %"],
    a: 1,
    e: "OEE = D × P × Q = 0,90 × 0,95 × 0,98 = 0,838 = 83,8 %. Un OEE « world class » est ≈ 85 %." },

  { phase: "Measure",
    q: "Lequel de ces événements réduit la composante « disponibilité » de l'OEE ?",
    o: ["Les micro-arrêts et ralentissements", "Les pannes et changements de série", "Les rebuts au démarrage", "Les retouches"],
    a: 1,
    e: "Disponibilité = temps de fonctionnement / temps planifié (pannes, changements). Performance = vitesse (micro-arrêts, cadence réduite). Qualité = bonnes pièces." },

  { phase: "Measure",
    q: "Dans une VSM, la ligne du temps en bas de la carte alterne des valeurs « en haut » et « en bas ». Que représentent-elles ?",
    o: ["Haut = temps de non-valeur ajoutée (attentes, stocks) ; bas = temps de traitement à valeur ajoutée",
        "Haut = coûts ; bas = délais",
        "Haut = flux d'information ; bas = flux physique",
        "Haut = temps machine ; bas = temps opérateur"],
    a: 0,
    e: "La ligne de temps sépare temps d'attente/stock (NVA, en haut) et temps de process (VA, en bas). Leur somme donne le lead time ; le rapport donne le PCE." },

  { phase: "Measure",
    q: "Dans une VSM, un stock de 500 pièces attend devant un poste dont la demande client est de 250 pièces/jour. Quel délai représente ce stock ?",
    o: ["0,5 jour", "2 jours", "500 jours", "250 jours"],
    a: 1,
    e: "Délai de stock = quantité / demande journalière = 500 / 250 = 2 jours (application de la loi de Little)." },

  { phase: "Measure",
    q: "Une cartographie détaillée du processus révèle des boucles de retouche et des points de décision. Quel type de carte est utilisé ?",
    o: ["Le SIPOC", "Le logigramme (flowchart) détaillé / swimlane", "Le diagramme de Pareto", "Le diagramme d'affinités"],
    a: 1,
    e: "Le logigramme détaillé (ou swimlane par acteur) documente chaque étape, décision et boucle. Le SIPOC reste macro (5–7 étapes)." },

  { phase: "Measure",
    q: "Dans un diagramme de cause à effet (Ishikawa), quelles sont les 6 M classiques ?",
    o: ["Main-d'œuvre, Machine, Méthode, Matière, Milieu, Mesure",
        "Marché, Marge, Mission, Management, Motivation, Moyens",
        "Moyenne, Médiane, Mode, Min, Max, Mesure",
        "Muda, Mura, Muri, Machine, Méthode, Milieu"],
    a: 0,
    e: "Les 6 M structurent le brainstorming des causes potentielles. En services, on utilise parfois les 4 P (Policies, Procedures, People, Plant)." },

  { phase: "Measure",
    q: "Quel outil pondère les entrées du processus (X) en fonction de leur impact sur les sorties clés (Y) pour prioriser les X à étudier ?",
    o: ["La matrice de cause à effet (matrice X-Y)", "Le SIPOC", "La droite de Henry", "Le diagramme spaghetti"],
    a: 0,
    e: "La matrice X-Y croise les X candidats (issus de la cartographie/Ishikawa) avec les Y pondérés par importance client ; elle réduit la liste avant l'AMDEC et l'analyse." },

  { phase: "Measure",
    q: "Dans une AMDEC, quelle note de Détection attribue-t-on à un mode de défaillance qu'aucun contrôle actuel ne peut détecter ?",
    o: ["1", "5", "10", "0"],
    a: 2,
    e: "L'échelle de Détection est inversée : 1 = détection quasi certaine, 10 = aucune détection possible. Gravité et Occurrence vont aussi de 1 (faible) à 10 (élevé)." },

  { phase: "Measure",
    q: "Dans une AMDEC, deux modes de défaillance ont le même RPN de 120 : A (G=10, O=3, D=4) et B (G=4, O=6, D=5). Lequel traiter en priorité ?",
    o: ["B, car l'occurrence est plus élevée", "A, car la gravité est maximale (sécurité/réglementation)", "Peu importe, les RPN sont égaux", "Aucun, 120 est acceptable"],
    a: 1,
    e: "À RPN égal, on priorise la gravité élevée (G = 9–10 impose une action quelle que soit la valeur du RPN). Le RPN seul est insuffisant." },

  { phase: "Measure",
    q: "Après une action corrective dans une AMDEC, sur quels facteurs peut-on réellement agir pour réduire le RPN ?",
    o: ["Uniquement la gravité", "L'occurrence (prévention) et la détection (contrôle) ; la gravité ne change que par reconception", "Uniquement la détection", "Les trois de manière équivalente"],
    a: 1,
    e: "La gravité de l'effet est intrinsèque au mode de défaillance ; on réduit surtout l'occurrence (éliminer la cause) puis la détection." },

  { phase: "Measure",
    q: "Une entreprise mesure la performance de base (baseline) du processus avant amélioration. Pourquoi est-ce indispensable ?",
    o: ["Pour choisir le Champion",
        "Pour quantifier l'écart initial et pouvoir démontrer statistiquement l'amélioration en fin de projet",
        "Pour réduire la taille de l'équipe",
        "Ce n'est pas indispensable"],
    a: 1,
    e: "Sans baseline (moyenne, σ, capabilité, DPMO), impossible de prouver le gain ni de fixer un objectif réaliste." },

  { phase: "Measure",
    q: "Un processus est dit « stable » si :",
    o: ["Son Cpk est supérieur à 1,33",
        "Il ne présente que des causes communes de variation (prévisible, sous contrôle statistique)",
        "Il produit zéro défaut",
        "Sa moyenne est égale à la cible"],
    a: 1,
    e: "Stabilité = maîtrise statistique (absence de causes spéciales). Capabilité = aptitude à respecter les spécifications. Un processus peut être stable mais non capable." },

  { phase: "Measure",
    q: "Pourquoi faut-il vérifier la stabilité du processus avant de calculer sa capabilité ?",
    o: ["Parce que la capabilité n'a de sens prédictif que si le processus est prévisible",
        "Parce que le calcul est impossible sinon",
        "Pour réduire la taille d'échantillon",
        "Ce n'est pas nécessaire"],
    a: 0,
    e: "Un indice Cpk calculé sur un processus instable ne prédit rien : la moyenne ou la dispersion peuvent changer à tout moment." },

  { phase: "Measure",
    q: "Quelle proportion de défauts long terme correspond approximativement à un Ppk de 1,0 (spécification bilatérale centrée) ?",
    o: ["0,27 % (2 700 ppm)", "3,4 ppm", "63 ppm", "4,55 %"],
    a: 0,
    e: "Ppk = 1 → limites à ±3σ → 0,27 % hors tolérance soit 2 700 ppm. Ppk 1,33 → 63 ppm ; Ppk 1,5 → 6,8 ppm." },

  { phase: "Measure",
    q: "Un processus a une spécification unilatérale USL = 50 (pas de LSL), μ = 44, σ = 2. Quel est le Cpk ?",
    o: ["1,00", "1,50", "0,50", "3,00"],
    a: 0,
    e: "Cpu = (USL − μ)/3σ = (50 − 44)/6 = 1,00. Sans LSL, Cpk = Cpu et Cp n'est pas défini." },

  { phase: "Measure",
    q: "Quel indice de capabilité pénalise l'écart de la moyenne par rapport à la cible T (et non par rapport aux limites) ?",
    o: ["Cp", "Cpk", "Cpm (indice de Taguchi)", "Pp"],
    a: 2,
    e: "Cpm = (USL − LSL) / (6 √(σ² + (μ − T)²)) intègre la perte de Taguchi liée à l'écart à la cible." },

  { phase: "Measure",
    q: "Dans une carte X̄-R avec sous-groupes de taille 5, R̄ = 4,65. Quel est l'estimateur de l'écart-type court terme ? (d₂ = 2,326 pour n = 5)",
    o: ["2,00", "10,8", "0,93", "4,65"],
    a: 0,
    e: "σ̂ = R̄/d₂ = 4,65 / 2,326 = 2,00. C'est l'écart-type intra-sous-groupe utilisé pour Cp/Cpk." },

  { phase: "Measure",
    q: "Une carte I-MR donne une étendue mobile moyenne MR̄ = 2,256. Quel est σ̂ court terme ? (d₂ = 1,128 pour n = 2)",
    o: ["2,00", "1,128", "2,54", "4,51"],
    a: 0,
    e: "σ̂ = MR̄/d₂ = 2,256 / 1,128 = 2,00." },

  { phase: "Measure",
    q: "Quel est le but de la « stratification » lors de la collecte de données ?",
    o: ["Réduire le nombre de mesures",
        "Enregistrer les facteurs contextuels (machine, équipe, fournisseur) pour pouvoir segmenter l'analyse",
        "Arrondir les mesures",
        "Éliminer les valeurs extrêmes"],
    a: 1,
    e: "Stratifier = collecter avec les « étiquettes » qui permettront de comparer les sous-populations et de découvrir des causes (ex. défauts par équipe)." },

  { phase: "Measure",
    q: "Une feuille de relevé (check sheet) sert principalement à :",
    o: ["Calculer la capabilité", "Collecter des données de manière structurée et standardisée en temps réel", "Analyser les causes racines", "Valider un plan d'expériences"],
    a: 1,
    e: "Le check sheet est un formulaire simple (souvent avec bâtons) pour compter défauts, occurrences ou localisations pendant l'opération." },

  { phase: "Measure",
    q: "Le temps de traitement d'une demande est mesuré en minutes. Il s'agit d'une échelle :",
    o: ["Nominale", "Ordinale", "De rapport (ratio)", "Binaire"],
    a: 2,
    e: "L'échelle de rapport possède un zéro absolu et des intervalles égaux : 20 min est deux fois 10 min. La température en °C est d'intervalle (zéro arbitraire)." },

  { phase: "Measure",
    q: "Une entreprise classe ses défauts par type : rayure, bosse, tache, manque. Quel type de donnée est la catégorie du défaut ?",
    o: ["Continue", "Ordinale", "Nominale", "De rapport"],
    a: 2,
    e: "Les catégories sans ordre naturel sont nominales. On les analyse avec un Pareto ou un chi-deux." },

  { phase: "Measure",
    q: "Quelle est la valeur de la médiane de {12, 7, 3, 9, 15, 10} ?",
    o: ["9", "9,5", "10", "12"],
    a: 1,
    e: "Triées : 3, 7, 9, 10, 12, 15. n pair → médiane = (9 + 10)/2 = 9,5." },

  { phase: "Measure",
    q: "Quel est l'étendue (range) de l'échantillon {14, 22, 9, 31, 18} ?",
    o: ["22", "18,8", "17", "31"],
    a: 0,
    e: "Étendue = max − min = 31 − 9 = 22. C'est la mesure de dispersion la plus simple, utilisée dans les cartes R." },

  { phase: "Measure",
    q: "La variance d'une population est 36. Quel est son écart-type ?",
    o: ["6", "18", "1 296", "36"],
    a: 0,
    e: "σ = √variance = √36 = 6. L'écart-type s'exprime dans l'unité des données, contrairement à la variance." },

  { phase: "Measure",
    q: "Pourquoi utilise-t-on n − 1 au dénominateur de la variance d'échantillon ?",
    o: ["Pour simplifier le calcul", "Pour obtenir un estimateur non biaisé de la variance de la population", "Parce que n est toujours inconnu", "Par convention historique sans justification"],
    a: 1,
    e: "Diviser par n sous-estime la variance de la population (les écarts sont mesurés à x̄, pas à μ). n − 1 (degrés de liberté) corrige ce biais." },

  { phase: "Measure",
    q: "Une entreprise a un rendement global de 95 % sur un processus de 10 étapes identiques en série. Quel est approximativement le rendement de chaque étape ?",
    o: ["95 %", "99,5 %", "90 %", "85 %"],
    a: 1,
    e: "Rendement par étape = RTY^(1/10) = 0,95^0,1 ≈ 0,9949 ≈ 99,5 %. Le RTY chute vite avec le nombre d'étapes." },

  { phase: "Measure",
    q: "Une opportunité de défaut est :",
    o: ["Toute unité produite", "Toute caractéristique mesurable d'une unité susceptible d'être non conforme", "Tout défaut constaté", "Toute réclamation client"],
    a: 1,
    e: "Les opportunités doivent être définies de façon stable et cohérente ; multiplier artificiellement les opportunités améliore faussement le DPMO." },

  { phase: "Measure",
    q: "Quel indicateur mesure la proportion d'unités qui traversent l'ensemble du processus sans aucun défaut ni retouche ?",
    o: ["FTY d'une étape", "RTY (rendement global de première passe)", "Yield final", "DPMO"],
    a: 1,
    e: "RTY = produit des FTY de toutes les étapes ; il révèle l'« usine cachée » que le yield final (après retouches) masque." },

  { phase: "Measure",
    q: "Une distribution uniforme continue entre 0 et 10 a pour moyenne :",
    o: ["0", "10", "5", "Indéterminée"],
    a: 2,
    e: "Moyenne de l'uniforme [a, b] = (a + b)/2 = 5. La variance vaut (b − a)²/12." },

  { phase: "Measure",
    q: "Un processus centré a une tolérance de ±0,6 mm et un écart-type court terme de 0,1 mm. Quel est le Cp ?",
    o: ["1,0", "2,0", "6,0", "0,5"],
    a: 1,
    e: "Cp = (USL − LSL)/6σ = 1,2 / 0,6 = 2,0 → processus 6σ court terme." },

  { phase: "Measure",
    q: "Le Ppk d'un processus est nettement inférieur à son Cpk. Que révèle cet écart ?",
    o: ["Une erreur de calcul",
        "Une variation entre sous-groupes (dérives, décalages) importante : le processus n'est pas stable dans le temps",
        "Un instrument non linéaire",
        "Une spécification trop large"],
    a: 1,
    e: "Cpk n'inclut que la variation intra-sous-groupe ; Ppk inclut aussi la variation inter-sous-groupes. Un grand écart signale des causes spéciales ou des dérives." },

  { phase: "Measure",
    q: "Pour des données attributs (proportion de défectueux p), comment estime-t-on le niveau sigma ?",
    o: ["Via Cp = p/6", "En convertissant p en DPMO puis en Z via la table normale (+1,5 shift)", "Impossible", "Via l'étendue R"],
    a: 1,
    e: "Défectueux → DPMO (ou DPO) → Z_LT = Φ⁻¹(1 − DPO) → Z_ST = Z_LT + 1,5. Ex. 1 % défectueux → Z_LT ≈ 2,33 → 3,83σ." },

  { phase: "Measure",
    q: "Lors d'un Gage R&R, le %GRR par rapport à la tolérance est de 8 % mais par rapport à la variation totale il est de 45 %. Comment interpréter ?",
    a: 1,
    o: ["Le système est inacceptable dans tous les cas",
        "Le système est apte à trier conforme/non conforme mais insuffisant pour piloter/améliorer le processus",
        "Le système est excellent dans tous les cas",
        "Les pièces sont trop dispersées"],
    e: "%GRR/tolérance juge l'aptitude au contrôle de conformité ; %GRR/TV juge l'aptitude à distinguer la variation du processus (nécessaire pour l'analyse et le SPC)." },

  { phase: "Measure",
    q: "Quel est le principal objectif de la phase Measure ?",
    o: ["Trouver la cause racine",
        "Établir une mesure fiable et la performance de base (baseline) du processus",
        "Déployer les solutions",
        "Former les opérateurs"],
    a: 1,
    e: "Measure : cartographier le processus, valider le système de mesure (MSA), collecter les données et quantifier la baseline (capabilité, niveau sigma)." },

  { phase: "Measure",
    q: "Une entreprise mesure la longueur de pièces avec un pied à coulisse gradué au mm alors que la tolérance est de ±0,2 mm. Quel est le problème ?",
    o: ["Aucun", "Résolution insuffisante : l'instrument ne peut pas discriminer la variation", "L'instrument est trop précis", "Le biais est trop faible"],
    a: 1,
    e: "Une résolution de 1 mm sur une tolérance de 0,4 mm viole la règle du 1/10 ; les mesures seront « en escalier » et les cartes R montreront des zéros artificiels." },

  { phase: "Measure",
    q: "Dans un processus, la moyenne mesurée est 100,2 pour une cible de 100 et un σ de 0,1 (tolérance ±0,5). Que peut-on dire ?",
    o: ["Cp = 1,67 et Cpk = 1,0", "Cp = 1,67 et Cpk = 1,67", "Cp = 1,0 et Cpk = 1,0", "Cp = 0,83 et Cpk = 0,5"],
    a: 0,
    e: "Cp = 1,0/0,6 = 1,67. Cpk = min[(100,5 − 100,2) ; (100,2 − 99,5)]/0,3 = 0,3/0,3 = 1,0. Recentrer ramènerait Cpk à 1,67." },

  { phase: "Measure",
    q: "Le 90ᵉ percentile des délais de livraison est de 6 jours. Cela signifie que :",
    o: ["90 % des livraisons prennent exactement 6 jours", "90 % des livraisons sont livrées en 6 jours ou moins", "La moyenne est de 6 jours", "10 % des livraisons prennent moins de 6 jours"],
    a: 1,
    e: "Le percentile P90 est la valeur en dessous de laquelle se situent 90 % des observations. Il est courant pour les CTQ de délai." },

  { phase: "Measure",
    q: "Une pièce mesurée à 10,04 mm avec un système de mesure dont l'incertitude est ±0,05 mm, pour une USL de 10,05 mm. Quel risque existe ?",
    o: ["Aucun, la pièce est conforme", "La pièce est dans la « zone grise » : elle peut être acceptée à tort ou rejetée à tort", "La pièce est certainement non conforme", "L'USL est fausse"],
    a: 1,
    e: "Près des limites, l'erreur de mesure crée des risques d'erreurs de tri (faux acceptés / faux rejetés) ; d'où l'importance d'un %GRR/tolérance faible." }
];
