// Phase MEASURE — partie 1 (55 questions)
const MEASURE_QUESTIONS_1 = [
  { phase: "Measure",
    q: "Un processus a des limites de spécification LSL = 10 et USL = 20. La moyenne mesurée est 16 et l'écart-type court terme est 1. Quelles sont les valeurs de Cp et Cpk ?",
    o: ["Cp = 1,33 ; Cpk = 1,67", "Cp = 1,67 ; Cpk = 1,33", "Cp = 1,67 ; Cpk = 2,00", "Cp = 3,33 ; Cpk = 1,33"],
    a: 1,
    e: "Cp = (20−10)/(6×1) = 1,67. Cpk = min[(20−16)/3 ; (16−10)/3] = min(1,33 ; 2,00) = 1,33. Cpk tient compte du centrage, Cp non." },

  { phase: "Measure",
    q: "Un processus en trois étapes a des rendements de première passe (FPY) de 95 %, 90 % et 98 %. Quel est le rendement global RTY (Rolled Throughput Yield) ?",
    o: ["83,8 %", "94,3 %", "90,0 %", "97,7 %"],
    a: 0,
    e: "RTY = produit des FPY = 0,95 × 0,90 × 0,98 = 0,838 soit 83,8 %. La moyenne des FPY (94,3 %) est un piège fréquent." },

  { phase: "Measure",
    q: "Une étude Gage R&R donne un %GRR (en % de la variation totale) de 25 %. Comment interpréter ce résultat selon les critères AIAG ?",
    o: ["Système de mesure acceptable sans réserve",
        "Système inacceptable, à remplacer immédiatement",
        "Système marginal, acceptable selon la criticité et le coût",
        "Résultat non interprétable sans le nombre de catégories distinctes"],
    a: 2,
    e: "Critères AIAG : < 10 % acceptable, 10–30 % marginal (conditionnellement acceptable), > 30 % inacceptable. 25 % est donc dans la zone marginale." },

  { phase: "Measure",
    q: "Un contrôle sur 1 500 unités révèle 45 défauts. Chaque unité comporte 5 opportunités de défaut. Quel est le DPMO ?",
    o: ["30 000", "150 000", "3 000", "6 000"],
    a: 3,
    e: "DPMO = défauts / (unités × opportunités) × 10⁶ = 45 / 7 500 × 10⁶ = 6 000. Oublier les opportunités donne 30 000." },

  { phase: "Measure",
    q: "Un instrument mesure 5 fois un étalon certifié à 10,00 mm et donne : 10,41 – 10,43 – 10,42 – 10,42 – 10,42. Comment qualifier ce système de mesure ?",
    o: ["Exact et précis", "Exact mais pas précis", "Précis mais pas exact", "Ni exact ni précis"],
    a: 2,
    e: "Les valeurs sont très groupées (bonne répétabilité = précision) mais décalées de +0,42 (biais = manque d'exactitude). Un étalonnage corrigera le biais." },

  { phase: "Measure",
    q: "On compte le nombre de rayures sur des panneaux de tôle dont la surface varie d'un lot à l'autre. Quelle carte de contrôle est la plus appropriée ?",
    o: ["Carte c", "Carte u", "Carte p", "Carte np", "Carte I-MR"],
    a: 1,
    e: "Comptage de défauts avec surface d'inspection variable → carte u (défauts par unité). La carte c exige une aire constante ; p et np concernent les défectueux." },

  { phase: "Measure",
    q: "Un processus présente 66 807 DPMO. Quel est approximativement son niveau sigma (avec le décalage conventionnel de 1,5 σ) ?",
    o: ["6 sigma", "4,5 sigma", "4 sigma", "3 sigma"],
    a: 3,
    e: "Table standard : 3σ ≈ 66 807 DPMO ; 4σ ≈ 6 210 ; 5σ ≈ 233 ; 6σ ≈ 3,4." },

  { phase: "Measure",
    q: "Quelle est la différence fondamentale entre Cpk et Ppk ?",
    o: ["Cpk ignore le centrage, Ppk en tient compte",
        "Cpk s'applique aux attributs, Ppk aux mesures continues",
        "Cpk utilise la variation court terme (intra-sous-groupe), Ppk la variation globale",
        "Cpk est calculé sur la population, Ppk sur un échantillon"],
    a: 2,
    e: "Cpk estime σ à partir de la variation intra-sous-groupe (R̄/d₂) ; Ppk utilise l'écart-type global. Les deux tiennent compte du centrage." },

  { phase: "Measure",
    q: "Une étude R&R par attributs entre deux inspecteurs donne un coefficient Kappa de 0,55. Comment interpréter ce résultat ?",
    o: ["Accord excellent, système validé", "Accord parfait entre les inspecteurs", "Accord acceptable pour toute application", "Accord faible, le système de mesure doit être amélioré"],
    a: 3,
    e: "Règle usuelle : Kappa ≥ 0,75 = bon accord ; 0,40–0,75 = à améliorer ; < 0,40 = inacceptable." },

  { phase: "Measure",
    q: "Dans une AMDEC processus, un mode de défaillance est évalué : Gravité = 8, Occurrence = 3, Détection = 5. Quel est son RPN ?",
    o: ["16", "40", "120", "24"],
    a: 2,
    e: "RPN = G × O × D = 8 × 3 × 5 = 120. C'est un produit, pas une somme." },

  { phase: "Measure",
    q: "Un processus est normalement distribué avec μ = 100 et σ = 5. La spécification supérieure est USL = 110. Quel pourcentage de pièces dépasse l'USL ?",
    o: ["2,28 %", "4,56 %", "0,13 %", "15,87 %"],
    a: 0,
    e: "z = (110 − 100)/5 = 2. P(Z > 2) = 2,28 % (queue unilatérale). 4,56 % = deux queues ; 15,87 % = z = 1." },

  { phase: "Measure",
    q: "Le nombre de réclamations reçues par jour est un exemple de quel type de donnée ?",
    o: ["Continue", "Discrète (comptage)", "Ordinale", "Nominale"],
    a: 1,
    e: "Un comptage d'événements est une donnée discrète (attribut). Continue = mesurable sur une échelle infinie (temps, longueur, poids)." },

  { phase: "Measure",
    q: "Une échelle de satisfaction « très insatisfait / insatisfait / neutre / satisfait / très satisfait » est une échelle :",
    o: ["Nominale", "Ordinale", "D'intervalle", "De rapport"],
    a: 1,
    e: "L'échelle ordinale a un ordre mais des écarts non quantifiables. Nominale = catégories sans ordre ; intervalle = écarts égaux sans zéro absolu ; rapport = zéro absolu." },

  { phase: "Measure",
    q: "Pourquoi les données continues sont-elles préférables aux données attributs pour un projet Six Sigma ?",
    o: ["Elles sont plus faciles à collecter",
        "Elles contiennent plus d'information et nécessitent des échantillons plus petits",
        "Elles ne nécessitent pas de MSA",
        "Elles sont toujours normales"],
    a: 1,
    e: "Une mesure continue (ex. 10,3 mm) informe plus qu'un simple conforme/non conforme ; les tests statistiques sont plus puissants avec moins de données." },

  { phase: "Measure",
    q: "Pour l'échantillon {4, 8, 6, 5, 7}, quelles sont la moyenne et la médiane ?",
    o: ["Moyenne 6 ; médiane 6", "Moyenne 6 ; médiane 5", "Moyenne 5 ; médiane 6", "Moyenne 6 ; médiane 7"],
    a: 0,
    e: "Moyenne = 30/5 = 6. Données triées : 4, 5, 6, 7, 8 → médiane = 6 (valeur centrale)." },

  { phase: "Measure",
    q: "Quel est l'écart-type de l'échantillon {2, 4, 4, 4, 5, 5, 7, 9} (formule échantillon, n−1) ?",
    o: ["2,00", "2,14", "4,00", "4,57"],
    a: 1,
    e: "Moyenne = 5. Somme des carrés des écarts = 9+1+1+1+0+0+4+16 = 32. s² = 32/7 = 4,57 ; s = 2,14. Avec n au dénominateur, on aurait 2,00 (population)." },

  { phase: "Measure",
    q: "Quelle mesure de tendance centrale est la moins sensible aux valeurs extrêmes (outliers) ?",
    o: ["La moyenne arithmétique", "La médiane", "La variance", "L'étendue"],
    a: 1,
    e: "La médiane dépend du rang, pas des valeurs extrêmes. La moyenne est tirée par les outliers. Variance et étendue sont des mesures de dispersion." },

  { phase: "Measure",
    q: "Dans une distribution fortement asymétrique à droite (skewness positive), quel est l'ordre typique des indicateurs ?",
    o: ["Moyenne < Médiane < Mode", "Mode < Médiane < Moyenne", "Médiane < Mode < Moyenne", "Moyenne = Médiane = Mode"],
    a: 1,
    e: "La queue à droite tire la moyenne vers les grandes valeurs : Mode < Médiane < Moyenne. L'égalité correspond à une distribution symétrique." },

  { phase: "Measure",
    q: "Dans une loi normale, quel pourcentage des valeurs se trouve dans l'intervalle μ ± 2σ ?",
    o: ["68,27 %", "95,45 %", "99,73 %", "50 %"],
    a: 1,
    e: "Règle empirique : ±1σ = 68,27 % ; ±2σ = 95,45 % ; ±3σ = 99,73 %." },

  { phase: "Measure",
    q: "Quelle proportion d'une population normale se situe hors de μ ± 3σ ?",
    o: ["0,27 %", "2,7 %", "4,55 %", "0,0034 %"],
    a: 0,
    e: "±3σ couvre 99,73 %, donc 0,27 % est à l'extérieur (0,135 % de chaque côté). C'est la base des limites de contrôle à 3σ." },

  { phase: "Measure",
    q: "Le coefficient de variation (CV) d'un processus est de 10 % avec une moyenne de 50. Quel est l'écart-type ?",
    o: ["0,2", "5", "500", "10"],
    a: 1,
    e: "CV = σ/μ → σ = CV × μ = 0,10 × 50 = 5. Le CV permet de comparer la dispersion de variables d'échelles différentes." },

  { phase: "Measure",
    q: "Quelle distribution modélise le nombre de défauts par unité (événements rares sur une aire d'opportunité) ?",
    o: ["Loi binomiale", "Loi de Poisson", "Loi normale", "Loi exponentielle"],
    a: 1,
    e: "Poisson : comptage d'événements sur un intervalle/une surface (cartes c et u). Binomiale : nombre de succès/défectueux sur n essais (cartes p et np)." },

  { phase: "Measure",
    q: "Quelle distribution modélise le nombre de pièces défectueuses dans un échantillon de n pièces, chaque pièce ayant une probabilité p d'être défectueuse ?",
    o: ["Loi de Poisson", "Loi binomiale", "Loi de Weibull", "Loi du chi-deux"],
    a: 1,
    e: "Binomiale : n essais indépendants, deux issues (conforme / défectueux), probabilité p constante. Moyenne = np, variance = np(1−p)." },

  { phase: "Measure",
    q: "Une loi binomiale a n = 100 et p = 0,05. Quelle est sa moyenne et son écart-type ?",
    o: ["μ = 5 ; σ ≈ 2,18", "μ = 5 ; σ = 5", "μ = 0,05 ; σ = 0,05", "μ = 95 ; σ ≈ 2,18"],
    a: 0,
    e: "μ = np = 5 ; σ = √(np(1−p)) = √(100 × 0,05 × 0,95) = √4,75 ≈ 2,18." },

  { phase: "Measure",
    q: "Pour une loi de Poisson de moyenne λ = 9, quel est l'écart-type ?",
    o: ["9", "3", "81", "4,5"],
    a: 1,
    e: "Dans la loi de Poisson, variance = λ, donc σ = √λ = √9 = 3." },

  { phase: "Measure",
    q: "Quelle distribution est souvent utilisée pour modéliser le temps entre deux pannes dans un processus à taux de défaillance constant ?",
    o: ["Loi normale", "Loi exponentielle", "Loi binomiale", "Loi uniforme"],
    a: 1,
    e: "L'exponentielle décrit le temps entre événements de Poisson (taux constant). La Weibull généralise avec un taux variable." },

  { phase: "Measure",
    q: "Un score z de −1,5 signifie que la valeur observée :",
    o: ["Est 1,5 fois la moyenne", "Se situe 1,5 écart-type en dessous de la moyenne", "Est inférieure de 1,5 unité à la moyenne", "A 1,5 % de chance d'apparaître"],
    a: 1,
    e: "z = (x − μ)/σ exprime l'écart à la moyenne en nombre d'écarts-types. Négatif = en dessous de la moyenne." },

  { phase: "Measure",
    q: "Un processus normal a μ = 50 et σ = 2. LSL = 46. Quelle proportion est sous la LSL ?",
    o: ["2,28 %", "15,87 %", "0,13 %", "4,56 %"],
    a: 0,
    e: "z = (46 − 50)/2 = −2 → P(Z < −2) = 2,28 %." },

  { phase: "Measure",
    q: "Un processus normal a μ = 50, σ = 2, LSL = 44 et USL = 54. Quelle proportion totale est hors spécification ?",
    o: ["0,135 %", "2,28 %", "2,41 %", "4,56 %"],
    a: 2,
    e: "z(LSL) = −3 → 0,135 % ; z(USL) = +2 → 2,28 %. Total = 2,41 %. Il faut sommer les deux queues." },

  { phase: "Measure",
    q: "Quelle est la formule de Cp ?",
    o: ["(USL − LSL) / 3σ", "(USL − LSL) / 6σ", "min(USL − μ ; μ − LSL) / 3σ", "(μ − LSL) / 6σ"],
    a: 1,
    e: "Cp = (USL − LSL)/(6σ) compare la largeur de la tolérance à la dispersion naturelle (±3σ). Cpk = min[(USL−μ), (μ−LSL)]/3σ." },

  { phase: "Measure",
    q: "Un processus a Cp = 2,0 et Cpk = 0,8. Que peut-on en déduire ?",
    o: ["Le processus est trop dispersé", "Le processus est bien centré mais dispersé", "Le processus a une faible dispersion mais est mal centré", "Les données ne sont pas normales"],
    a: 2,
    e: "Cp élevé = dispersion faible par rapport à la tolérance. Cpk << Cp = décentrage important. Recentrer le processus ferait tendre Cpk vers Cp." },

  { phase: "Measure",
    q: "Quelle valeur minimale de Cpk est généralement exigée pour qu'un processus existant soit considéré comme capable ?",
    o: ["0,67", "1,00", "1,33", "2,00"],
    a: 2,
    e: "Cpk ≥ 1,33 (4σ de marge) est le seuil usuel pour un processus existant ; 1,67 pour un nouveau processus ; 2,0 correspond à 6σ court terme." },

  { phase: "Measure",
    q: "Un processus a Cpk = 1,0 (court terme). Quel niveau sigma court terme cela représente-t-il ?",
    o: ["1 sigma", "3 sigma", "4,5 sigma", "6 sigma"],
    a: 1,
    e: "Niveau sigma court terme Z = 3 × Cpk. Cpk = 1 → 3σ ; Cpk = 1,33 → 4σ ; Cpk = 2 → 6σ." },

  { phase: "Measure",
    q: "Que représente le décalage de 1,5 sigma utilisé dans les tables Six Sigma ?",
    o: ["L'erreur de mesure typique d'un instrument",
        "La dérive attendue de la moyenne d'un processus à long terme",
        "La marge de sécurité des limites de contrôle",
        "L'écart entre Cp et Pp"],
    a: 1,
    e: "Empiriquement, la moyenne d'un processus dérive d'environ ±1,5σ à long terme. Z_LT = Z_ST − 1,5. Ainsi 6σ court terme ≈ 4,5σ long terme = 3,4 DPMO." },

  { phase: "Measure",
    q: "Un processus a un DPMO de 6 210. Quel est son niveau sigma (avec décalage 1,5σ) ?",
    o: ["3σ", "4σ", "5σ", "2σ"],
    a: 1,
    e: "Repères : 2σ = 308 537 ; 3σ = 66 807 ; 4σ = 6 210 ; 5σ = 233 ; 6σ = 3,4 DPMO." },

  { phase: "Measure",
    q: "Sur 500 formulaires contrôlés, 60 contiennent au moins une erreur. Quel est le rendement (yield) et le taux de défectueux ?",
    o: ["Yield 88 % ; défectueux 12 %", "Yield 12 % ; défectueux 88 %", "Yield 94 % ; défectueux 6 %", "Yield 60 % ; défectueux 40 %"],
    a: 0,
    e: "Défectueux = 60/500 = 12 % ; yield = 1 − 0,12 = 88 %. Un formulaire défectueux peut contenir plusieurs défauts." },

  { phase: "Measure",
    q: "Quelle est la différence entre un « défaut » et un « défectueux » ?",
    o: ["Aucune, ce sont des synonymes",
        "Un défaut est une non-conformité ; un défectueux est une unité comportant au moins un défaut",
        "Un défectueux est réparable, un défaut ne l'est pas",
        "Un défaut concerne les services, un défectueux les produits"],
    a: 1,
    e: "Une unité peut porter plusieurs défauts mais ne compte que comme un seul défectueux. Défauts → Poisson (c, u) ; défectueux → binomiale (p, np)." },

  { phase: "Measure",
    q: "Un processus produit 2 000 unités avec 100 défauts au total. Quel est le DPU (défauts par unité) ?",
    o: ["0,05", "20", "0,5", "5"],
    a: 0,
    e: "DPU = défauts / unités = 100 / 2 000 = 0,05." },

  { phase: "Measure",
    q: "Un processus a un DPU de 0,2. Quelle est l'estimation du rendement de première passe FTY via la loi de Poisson ?",
    o: ["80 %", "81,9 %", "20 %", "98 %"],
    a: 1,
    e: "FTY ≈ e^(−DPU) = e^(−0,2) ≈ 0,819. L'approximation 1 − DPU = 80 % est proche mais moins exacte." },

  { phase: "Measure",
    q: "Une étape produit 1 000 unités ; 100 sont retouchées puis acceptées et 20 sont rebutées. Quelle est la différence entre le rendement final et le FPY ?",
    o: ["Rendement final 98 %, FPY 88 %", "Rendement final 88 %, FPY 98 %", "Les deux valent 98 %", "Les deux valent 88 %"],
    a: 0,
    e: "Rendement final = 980/1 000 = 98 % (cache la retouche). FPY = (1 000 − 100 − 20)/1 000 = 88 % (bonnes du premier coup). La retouche est l'« usine cachée »." },

  { phase: "Measure",
    q: "Le rendement normalisé (Normalized Yield) d'un processus à 4 étapes dont le RTY est 0,81 vaut :",
    o: ["0,81", "0,2025", "0,9487", "0,95"],
    a: 2,
    e: "Rendement normalisé = RTY^(1/k) = 0,81^(1/4) = √(√0,81) = √0,9 ≈ 0,9487. C'est le rendement moyen par étape." },

  { phase: "Measure",
    q: "Quelles sont les deux composantes de la variation du système de mesure évaluées dans un Gage R&R ?",
    o: ["Exactitude et linéarité", "Répétabilité et reproductibilité", "Stabilité et biais", "Résolution et étendue"],
    a: 1,
    e: "Répétabilité = variation de l'équipement (même opérateur, même pièce). Reproductibilité = variation entre opérateurs (ou évaluateurs)." },

  { phase: "Measure",
    q: "Dans une étude Gage R&R, la répétabilité est élevée. Quelle est la source de variation la plus probable ?",
    o: ["Les différences de méthode entre opérateurs", "L'instrument de mesure lui-même", "La formation des opérateurs", "La différence entre les pièces"],
    a: 1,
    e: "Répétabilité (EV, Equipment Variation) = variation observée quand le même opérateur remesure la même pièce ; elle incrimine l'instrument ou le montage." },

  { phase: "Measure",
    q: "Dans une étude Gage R&R, la reproductibilité domine. Quelle action est prioritaire ?",
    o: ["Remplacer l'instrument", "Standardiser la méthode et former les opérateurs", "Augmenter le nombre de pièces", "Réduire la tolérance"],
    a: 1,
    e: "Reproductibilité (AV, Appraiser Variation) = variation entre opérateurs ; elle se corrige par une définition opérationnelle claire, une méthode standard et une formation." },

  { phase: "Measure",
    q: "Un Gage R&R indique un nombre de catégories distinctes (ndc) de 3. Que conclure ?",
    o: ["Le système est excellent", "Le système ne discrimine pas suffisamment les pièces ; ndc ≥ 5 est requis", "ndc n'a pas d'importance", "Il faut 3 opérateurs"],
    a: 1,
    e: "ndc = 1,41 × (variation pièces / variation R&R). AIAG exige ndc ≥ 5 pour que le système distingue correctement les pièces entre elles." },

  { phase: "Measure",
    q: "Qu'est-ce que la linéarité d'un système de mesure ?",
    o: ["La capacité à donner les mêmes résultats dans le temps",
        "La variation du biais sur l'étendue de mesure de l'instrument",
        "La plus petite graduation lisible",
        "L'accord entre deux opérateurs"],
    a: 1,
    e: "Linéarité = évolution du biais selon la valeur mesurée (ex. juste à 10 mm, biaisé à 100 mm). Stabilité = constance du biais dans le temps." },

  { phase: "Measure",
    q: "Selon la règle du 1/10 (règle de résolution), un instrument destiné à mesurer une tolérance de 0,5 mm doit avoir une résolution d'au plus :",
    o: ["0,5 mm", "0,1 mm", "0,05 mm", "5 mm"],
    a: 2,
    e: "Règle empirique : la résolution doit être ≤ 1/10 de la tolérance (ou de la variation du processus) → 0,5/10 = 0,05 mm." },

  { phase: "Measure",
    q: "Quelle propriété du système de mesure est évaluée en mesurant régulièrement le même étalon sur plusieurs semaines et en traçant une carte de contrôle ?",
    o: ["La répétabilité", "La reproductibilité", "La stabilité", "La linéarité"],
    a: 2,
    e: "La stabilité (dérive) est la variation du biais dans le temps ; on la suit par une carte de contrôle sur un étalon." },

  { phase: "Measure",
    q: "Le biais d'un instrument est de +0,3 mm. Quelle action est appropriée ?",
    o: ["Remplacer l'opérateur", "Étalonner / ajuster l'instrument", "Augmenter la taille d'échantillon", "Changer la spécification"],
    a: 1,
    e: "Le biais est un écart systématique entre la moyenne mesurée et la valeur de référence ; il se corrige par étalonnage." },

  { phase: "Measure",
    q: "Dans un Gage R&R croisé standard, quelle configuration est typiquement recommandée ?",
    o: ["3 opérateurs, 10 pièces, 2 à 3 répétitions", "1 opérateur, 30 pièces, 1 répétition", "10 opérateurs, 3 pièces, 1 répétition", "2 opérateurs, 2 pièces, 10 répétitions"],
    a: 0,
    e: "Configuration AIAG classique : 10 pièces couvrant l'étendue du processus, 2–3 opérateurs, 2–3 mesures chacune, dans un ordre aléatoire." },

  { phase: "Measure",
    q: "Dans un Gage R&R, que signifie une interaction opérateur × pièce significative ?",
    o: ["Les opérateurs mesurent certaines pièces différemment des autres",
        "L'instrument n'est pas linéaire",
        "Les pièces sont toutes identiques",
        "La répétabilité est nulle"],
    a: 0,
    e: "L'interaction indique que l'écart entre opérateurs dépend de la pièce (ex. un opérateur lit mal les grosses pièces). Elle est intégrée à la reproductibilité." },

  { phase: "Measure",
    q: "Pourquoi les pièces d'une étude Gage R&R doivent-elles être choisies pour couvrir toute l'étendue de variation du processus ?",
    o: ["Pour réduire le temps d'étude",
        "Pour que le %GRR (par rapport à la variation totale) et le ndc soient représentatifs",
        "Pour éliminer la reproductibilité",
        "Ce n'est pas nécessaire"],
    a: 1,
    e: "Si les pièces sont trop semblables, la variation pièce est sous-estimée et le %GRR/TV paraît artificiellement mauvais. Le %GRR/tolérance, lui, ne dépend pas des pièces." },

  { phase: "Measure",
    q: "Dans une étude R&R par attributs, quel indicateur mesure l'accord d'un évaluateur avec lui-même lors de répétitions ?",
    o: ["Le Kappa inter-évaluateurs", "La répétabilité (accord intra-évaluateur)", "L'efficacité contre le standard", "Le taux de fausses alarmes"],
    a: 1,
    e: "L'accord intra-évaluateur (within appraiser) mesure la cohérence d'un même inspecteur ; l'accord inter-évaluateurs mesure la cohérence entre inspecteurs ; l'efficacité compare au standard connu." },

  { phase: "Measure",
    q: "Une définition opérationnelle doit :",
    o: ["Être connue uniquement du Black Belt",
        "Décrire précisément quoi mesurer, comment et avec quel critère, pour que tous obtiennent le même résultat",
        "Être exprimée en termes statistiques uniquement",
        "Être révisée après chaque mesure"],
    a: 1,
    e: "La définition opérationnelle supprime l'ambiguïté (ex. « délai = de l'horodatage réception à l'horodatage d'envoi »). C'est un prérequis à toute collecte fiable." },

  { phase: "Measure",
    q: "Quel élément d'un plan de collecte de données définit qui collecte, quand, où, comment et à quelle fréquence ?",
    o: ["Le SIPOC", "La feuille de relevé (check sheet) et le plan d'échantillonnage", "Le business case", "La carte de contrôle"],
    a: 1,
    e: "Le plan de collecte précise la métrique, sa définition opérationnelle, le type de donnée, la méthode d'échantillonnage, la fréquence, le responsable et le support (check sheet)." }
];
